export enum Types {
  Text = 'text',
  File = 'file',
  Hidden = 'hidden',
  Image = 'image',
  Password = 'password',
  Color = 'color',
  Date = 'date',
  DateTime = 'datetime',
  DateTimeLocal = 'datetime-local',
  Email = 'email',
  Number = 'number',
  Range = 'range',
  Search = 'search',
  Tel = 'tel',
  Time = 'time',
  Url = 'url',
  Month = 'month',
  Week = 'week',
}
