import { css } from '@linaria/core';

import {
  COLORS,
  COLORS_AVATAR,
  COLORS_BADGE,
  COLORS_BREADCRUMBS,
  COLORS_BUTTON,
  COLORS_CARD,
  COLORS_CHECKBOX,
  COLORS_COLLAPSE_PANEL,
  COLORS_DIVIDER,
  COLORS_DRAWER,
  COLORS_FILTER,
  COLORS_FORM_FIELD,
  COLORS_FORM_GROUP,
  COLORS_GENERAL,
  COLORS_ICON,
  COLORS_ICON_BUTTON,
  COLORS_INPUT,
  COLORS_LOGS_VIEW,
  COLORS_MODAL,
  COLORS_NO_DATA_PAGE,
  COLORS_PAGINATE,
  COLORS_RADIO,
  COLORS_SELECT,
  COLORS_SLIDER,
  COLORS_SPIN,
  COLORS_STATUS,
  COLORS_SWITCH,
  COLORS_TABLE,
  COLORS_TABS,
  COLORS_TAG,
  COLORS_TOAST,
  COLORS_TOOLBAR,
  COLORS_TOOLTIP,
  COLORS_TYPOGRAPHY,
  TABLE_BUTTON_COLORS,
} from './vars';

export const purpleDark = css`
  :global() {
    [data-theme='purpleDark'] {
      ${COLORS.GRAY_1}: #c6c6c6;
      ${COLORS.GRAY_2}: #a0a0a0;
      ${COLORS.GRAY_3}: #898989;
      ${COLORS.GRAY_4}: #838383;
      ${COLORS.GRAY_5}: #6d6d6d;
      ${COLORS.GRAY_6}: #484848;
      ${COLORS.GRAY_7}: #414141;
      ${COLORS.GRAY_8}: #313131;
      ${COLORS.BLACK_1}: #252525;
      ${COLORS.BLACK_2}: #171717;
      ${COLORS.WHITE}: #ffffff;
      ${COLORS.VIOLET_1}: #f3f3f3;
      ${COLORS.VIOLET_2}: #e5e6fe;
      ${COLORS.VIOLET_3}: #aaabfc;
      ${COLORS.VIOLET_4}: #a9abff;
      ${COLORS.VIOLET_5}: #5558fa;
      ${COLORS.VIOLET_6}: #484bd5;
      ${COLORS.VIOLET_7}: #4042bc;
      ${COLORS.VIOLET_8}: #2f3065;
      ${COLORS.PURPLE}: #5C00EC;
      ${COLORS.GREEN_1}: #12bba6;
      ${COLORS.GREEN_2}: #00ea95;
      ${COLORS.GREEN_3}: #07e897;
      ${COLORS.BLUE_1}: #375EC9;
      ${COLORS.BLUE_2}: #258CB8;
      ${COLORS.RED_1}: #e84e58;
      ${COLORS.RED_2}: #ff0000;
      ${COLORS.YELLOW}: #F0D559;

      ${COLORS_GENERAL.BACKGROUND}: var(${COLORS.BLACK_2});
      ${COLORS_GENERAL.TEXT}: var(${COLORS.GRAY_1});

      ${COLORS_TYPOGRAPHY.LINK}: var(${COLORS.VIOLET_5});

      ${COLORS_BUTTON.FOCUS_SHADOW}: var(${COLORS.VIOLET_8});

      ${COLORS_BUTTON.FILLED_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.FILLED_ICON_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.FILLED_BG}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.FILLED_HOVER_BG}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.FILLED_ACTIVE_BG}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.FILLED_DISABLED_COLOR}: var(${COLORS.GRAY_5});
      ${COLORS_BUTTON.FILLED_DISABLED_BG}: var(${COLORS.VIOLET_8});
      ${COLORS_BUTTON.FILLED_FOCUS_BG}: var(${COLORS.VIOLET_6});

      ${COLORS_BUTTON.OUTLINED_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.OUTLINED_BORDER}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.OUTLINED_HOVER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.OUTLINED_HOVER_BORDER}: var(${COLORS.VIOLET_3});
      ${COLORS_BUTTON.OUTLINED_ACTIVE_COLOR}: var(${COLORS.VIOLET_3});
      ${COLORS_BUTTON.OUTLINED_ACTIVE_BORDER}: var(${COLORS.VIOLET_3});
      ${COLORS_BUTTON.OUTLINED_DISABLED_COLOR}: #aaabfc4d;
      ${COLORS_BUTTON.OUTLINED_DISABLED_BORDER}: #aaabfc4d;
      ${COLORS_BUTTON.OUTLINED_FOCUS_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.OUTLINED_FOCUS_BORDER}: var(${COLORS.VIOLET_5});

      ${COLORS_BUTTON.TRANSPARENT_COLOR}: var(${COLORS.VIOLET_3});
      ${COLORS_BUTTON.TRANSPARENT_HOVER_BG}: var(${COLORS.GRAY_8});
      ${COLORS_BUTTON.TRANSPARENT_HOVER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.TRANSPARENT_ACTIVE_BG}: var(${COLORS.BLACK_1});
      ${COLORS_BUTTON.TRANSPARENT_ACTIVE_COLOR}: var(${COLORS.VIOLET_3});
      ${COLORS_BUTTON.TRANSPARENT_DISABLED_COLOR}: var(${COLORS.GRAY_5});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_BG}: var(${COLORS.GRAY_8});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_BORDER}: var(${COLORS.VIOLET_6});

      ${COLORS_BUTTON.FILLED_BRAND_COLOR}: #343f48;
      ${COLORS_BUTTON.FILLED_BRAND_BG}: #07e897;
      ${COLORS_BUTTON.FILLED_BRAND_HOVER_BG}: #07d88d;
      ${COLORS_BUTTON.FILLED_BRAND_ACTIVE_BG}: #07cc85;
      ${COLORS_BUTTON.FILLED_BRAND_DISABLED_COLOR}: #cfcfcf;
      ${COLORS_BUTTON.FILLED_BRAND_DISABLED_BG}: #ededed;
      ${COLORS_BUTTON.FILLED_BRAND_FOCUS_BG}: #07d88d;

      ${COLORS_BUTTON.TABLE_MENU_BUTTON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_BUTTON.TABLE_MENU_BUTTON_HOVER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.TABLE_MENU_BUTTON_DISABLED_COLOR}: #454545;
      ${COLORS_BUTTON.TABLE_MENU_BUTTON_ACTIVE_COLOR}: var(${COLORS.WHITE});

      ${COLORS_BUTTON.WHITE_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.WHITE_BG}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.WHITE_HOVER_BG}: var(${COLORS.VIOLET_2});
      ${COLORS_BUTTON.WHITE_HOVER_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.WHITE_ACTIVE_BG}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.WHITE_ACTIVE_COLOR}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.WHITE_DISABLED_COLOR}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.WHITE_DISABLED_BG}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.WHITE_FOCUS_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.WHITE_FOCUS_BG}: var(${COLORS.VIOLET_2});
      ${COLORS_BUTTON.WHITE_FOCUS_OUTLINE}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.WHITE_FOCUS_BORDER}: var(${COLORS.VIOLET_6});

      ${COLORS_ICON.FILL}: var(${COLORS.GRAY_3});
      ${COLORS_ICON.HOVER_FILL}: var(${COLORS.VIOLET_5});
      ${COLORS_ICON.ACTIVE_FILL}: var(${COLORS.GRAY_2});

      ${COLORS_DIVIDER.COLOR_LIGHT}: var(${COLORS.BLACK_1});
      ${COLORS_DIVIDER.COLOR_MIDDLE}: var(${COLORS.GRAY_8});
      ${COLORS_DIVIDER.COLOR_DARK}: var(${COLORS.GRAY_6});

      ${COLORS_SPIN.BORDER}: var(${COLORS.WHITE});
      ${COLORS_SPIN.BORDER_TOP}: #ffffff33;
      ${COLORS_SPIN.TEXT_COLOR}: var(${COLORS.WHITE});

      ${COLORS_SPIN.BORDER_REV}: var(${COLORS.GRAY_3});
      ${COLORS_SPIN.BORDER_REV_TOP}: var(${COLORS.GRAY_1});
      ${COLORS_SPIN.TEXT_REV_COLOR}: var(${COLORS.BLACK_2});

      ${COLORS_MODAL.BG}: var(${COLORS.GRAY_8});
      ${COLORS_MODAL.TITLE_COLOR}: var(${COLORS.WHITE});
      ${COLORS_MODAL.DESCRIPTION_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_MODAL.PREVIEW_BG}: var(${COLORS.GRAY_8});
      ${COLORS_MODAL.PREVIEW_CLOSE_ICON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_MODAL.PREVIEW_CLOSE_ICON_HOVER_COLOR}: var(${COLORS.WHITE});

      ${COLORS_TOOLTIP.CONTAINER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TOOLTIP.CONTAINER_BG}: var(${COLORS.VIOLET_5});
      ${COLORS_TOOLTIP.MENU_BG}: var(${COLORS.GRAY_8});
      ${COLORS_TOOLTIP.MENU_ITEM_HOVER_BG}: var(${COLORS.GRAY_7});
      ${COLORS_TOOLTIP.ICON_FILL}: var(${COLORS.VIOLET_3});
      ${COLORS_TOOLTIP.ICON_HOVER_FILL}: var(${COLORS.WHITE});

      ${COLORS_TAG.TAG_TEXT_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TAG.TAG_BG_GREEN}: #527771;
      ${COLORS_TAG.TAG_BG_BLUE}: #517086;
      ${COLORS_TAG.TAG_BG_PURPLE}: #6a5b8c;
      ${COLORS_TAG.TAG_BG_PINK}: #8a5273;
      ${COLORS_TAG.TAG_BG_RED}: #98605b;
      ${COLORS_TAG.TAG_BG_GRAY_DEFAULT}: #6c6f71;
      ${COLORS_TAG.TAG_BG_GRAY}: #515558;
      ${COLORS_TAG.TAG_BG_BROWN}: #685c56;
      ${COLORS_TAG.TAG_BG_ORANGE}: #9a754f;
      ${COLORS_TAG.TAG_BG_YELLOW}: #9e9056;
      ${COLORS_TAG.TAG_BG_YELLOW_GREEN}: #6d7b4e;
      ${COLORS_TAG.TAG_BG_BLUE_GREEN}: #146c6c;
      ${COLORS_TAG.TAG_TYPE_CARD_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_TAG.TAG_TYPE_CARD_BACKGROUND}: var(${COLORS.BLACK_1});

      ${COLORS_INPUT.INPUT_BG}: var(${COLORS.GRAY_8});
      ${COLORS_INPUT.INPUT_BORDER}: var(${COLORS.GRAY_7});
      ${COLORS_INPUT.INPUT_ERROR_BORDER}: var(${COLORS.RED_1});
      ${COLORS_INPUT.INPUT_PLACEHOLDER_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_INPUT.INPUT_TEXT_COLOR}: var(${COLORS.WHITE});
      ${COLORS_INPUT.INPUT_FOCUS_BORDER}: var(${COLORS.GRAY_3});
      ${COLORS_INPUT.INPUT_FOCUS_BACKGROUND}: var(${COLORS.GRAY_7});
      ${COLORS_INPUT.INPUT_HOVER_BORDER}: var(${COLORS.GRAY_6});
      ${COLORS_INPUT.INPUT_HOVER_PLACEHOLDER_COLOR}: var(${COLORS.GRAY_1});
      ${COLORS_INPUT.INPUT_HOVER_BACKGROUND}: var(${COLORS.GRAY_7});
      ${COLORS_INPUT.INPUT_ERROR}: var(${COLORS.RED_1});
      ${COLORS_INPUT.INPUT_DISABLED_BACKGROUND}: var(${COLORS.BLACK_1});
      ${COLORS_INPUT.INPUT_DISABLED_COLOR}: var(${COLORS.GRAY_5});
      ${COLORS_INPUT.INPUT_DISABLED_BORDER}: var(${COLORS.GRAY_7});
      ${COLORS_INPUT.INPUT_ICON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_INPUT.INPUT_ICON_HOVER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_INPUT.COPY_INPUT_BACKGROUND}: var(${COLORS.BLACK_1});
      ${COLORS_INPUT.COPY_INPUT_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_INPUT.COPY_INPUT_ICON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_INPUT.COPY_INPUT_ICON_HOVER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_INPUT.COPY_INPUT_ICON_BACKGROUND_COLOR}: var(${COLORS.GRAY_8});

      ${COLORS_RADIO.COLOR}: var(${COLORS.GRAY_1});
      ${COLORS_RADIO.SECONDARY_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_RADIO.DISABLED_COLOR}: var(${COLORS.GRAY_5});
      ${COLORS_RADIO.HOVER_BG}: var(${COLORS.GRAY_7});
      ${COLORS_RADIO.CHECKED_BG}: var(${COLORS.GRAY_8});
      ${COLORS_RADIO.ICON_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_RADIO.ICON_BG}: var(${COLORS.BLACK_1});
      ${COLORS_RADIO.ICON_HOVER_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_RADIO.ICON_DISABLED_COLOR}: #454545;
      ${COLORS_RADIO.CHECKED_ICON_COLOR}: var(${COLORS.VIOLET_3});
      ${COLORS_RADIO.CHECKED_ICON_HOVER_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_RADIO.CHECKED_ICON_DISABLED_COLOR}: #454545;

      ${COLORS_SELECT.TEXT_COLOR}: var(${COLORS.WHITE});
      ${COLORS_SELECT.TEXT_OPTION_DISABLED_COLOR}: var(${COLORS.GRAY_5});
      ${COLORS_SELECT.GROUP_HEADING_TEXT_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_SELECT.PLACEHOLDER_TEXT_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_SELECT.BACKGROUND}: var(${COLORS.GRAY_8});
      ${COLORS_SELECT.BACKGROUND_HOVER}: var(${COLORS.GRAY_7});
      ${COLORS_SELECT.BACKGROUND_WITH_LOGO}: var(${COLORS.GRAY_8});
      ${COLORS_SELECT.BACKGROUND_WITH_LOGO_HOVER}: var(${COLORS.GRAY_7});
      ${COLORS_SELECT.BORDER_COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_SELECT.BORDER_HOVER_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_SELECT.BORDER_FOCUS_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_SELECT.DISABLED_BORDER_COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_SELECT.DISABLED_TEXT_COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_SELECT.DISABLED_BACKGROUND}: var(${COLORS.BLACK_1});
      ${COLORS_SELECT.DROPDOWN_BACKGROUND}: var(${COLORS.GRAY_8});
      ${COLORS_SELECT.DROPDOWN_HOVER_BACKGROUND}: var(${COLORS.GRAY_7});
      ${COLORS_SELECT.DROPDOWN_FOCUS_BACKGROUND}: var(${COLORS.GRAY_6});
      ${COLORS_SELECT.DROPDOWN_ICON_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_SELECT.DROPDOWN_ICON_HOVER_COLOR}: var(${COLORS.WHITE});

      ${COLORS_BADGE.BORDER_COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_BADGE.TEXT_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BADGE.DEFAULT_BACKGROUND}: var(${COLORS.VIOLET_5});

      ${COLORS_TOOLBAR.BACKGROUND}: var(${COLORS.GRAY_8});
      ${COLORS_TOOLBAR.INPUT_BORDER}: var(${COLORS.GRAY_3});
      ${COLORS_TOOLBAR.ACTIVE_BUTTON}: var(${COLORS.WHITE});
      ${COLORS_TOOLBAR.PLACEHOLDER_COLOR}: var(${COLORS.GRAY_2});

      ${COLORS_CHECKBOX.CHECKBOX_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_CHECKBOX.CHECKBOX_HOVER_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_CHECKBOX.CHECKBOX_DISABLED_COLOR}: #454545;
      ${COLORS_CHECKBOX.CHECKBOX_DISABLED_TEXT_COLOR}: #454545;
      ${COLORS_CHECKBOX.CHECKBOX_FILLED_COLOR}: var(${COLORS.VIOLET_3});
      ${COLORS_CHECKBOX.CHECKBOX_FILLED_HOVER_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_CHECKBOX.CHECKBOX_FILLED_DISABLED_COLOR}: #454545;
      ${COLORS_CHECKBOX.CHECKBOX_PART_CHECKED_RECT_COLOR}: var(${COLORS.BLACK_2});

      ${COLORS_CARD.CARD_BACKGROUND}: var(${COLORS.GRAY_8});
      ${COLORS_CARD.CARD_HOVER_BACKGROUND}: var(${COLORS.GRAY_7});
      ${COLORS_CARD.CARD_SELECTED_BACKGROUND}: var(${COLORS.GRAY_6});
      ${COLORS_CARD.CARD_HOVER_SHADOW}: transparent;
      ${COLORS_CARD.CARD_FAVOURITE_ICON_COLOR}: #d2d2d2;
      ${COLORS_CARD.CARD_FAVOURITE_ICON_HOVER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_CARD.CARD_FAVOURITE_ICON_FILLED_COLOR}: var(${COLORS.YELLOW});

      ${COLORS_PAGINATE.PAGINATE_ACTIVE_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_PAGINATE.PAGINATE_DISABLED_COLOR}: var(${COLORS.VIOLET_3});
      ${COLORS_PAGINATE.PAGINATE_WHITE_COLOR}: var(${COLORS.WHITE});

      ${COLORS_COLLAPSE_PANEL.COLLAPSE_PANEL_BACKGROUND}: var(${COLORS.GRAY_8});
      ${COLORS_COLLAPSE_PANEL.COLLAPSE_PANEL_BACKGROUND_HOVER}: var(${COLORS.GRAY_7});
      ${COLORS_COLLAPSE_PANEL.COLLAPSE_PANEL_FAVOURITE_ICON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_COLLAPSE_PANEL.COLLAPSE_PANEL_FAVOURITE_ICON_HOVER_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_COLLAPSE_PANEL.COLLAPSE_PANEL_FAVOURITE_ICON_FILLED_COLOR}: var(${COLORS.YELLOW});

      ${COLORS_TABS.TAB_ACTIVE_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_TABS.TAB_BORDER_COLOR}: #ededed;
      ${COLORS_TABS.TAB_GRAY_BORDER_COLOR}: #d2d2d2;
      ${COLORS_TABS.TAB_TEXT_COLOR}: var(${COLORS.GRAY_2});

      ${COLORS_STATUS.COLOR}: var(${COLORS.GRAY_1});
      ${COLORS_STATUS.FAILED_BG}: var(${COLORS.RED_2});
      ${COLORS_STATUS.SUCCESS_BG}: var(${COLORS.GREEN_3});
      ${COLORS_STATUS.WARNING_BG}: var(${COLORS.YELLOW});
      ${COLORS_STATUS.UNACTIVE_BG}: var(${COLORS.GRAY_3});

      ${COLORS_SWITCH.UNACTIVE_BG}: var(${COLORS.GRAY_4});
      ${COLORS_SWITCH.UNACTIVE_HOVER_BG}: var(${COLORS.GRAY_3});
      ${COLORS_SWITCH.UNACTIVE_DISABLED_BG}: var(${COLORS.GRAY_6});
      ${COLORS_SWITCH.ACTIVE_BG}: var(${COLORS.VIOLET_5});
      ${COLORS_SWITCH.ACTIVE_HOVER_BG}: var(${COLORS.VIOLET_6});
      ${COLORS_SWITCH.ACTIVE_DISABLED_BG}: var(${COLORS.VIOLET_3});

      ${COLORS_BREADCRUMBS.ACTIVE_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BREADCRUMBS.INACTIVE_COLOR}: var(${COLORS.GRAY_1});

      ${COLORS_DRAWER.HEADER_TEXT_COLOR}: var(${COLORS.WHITE});
      ${COLORS_DRAWER.BACKGROUND}: var(${COLORS.BLACK_1});
      ${COLORS_DRAWER.BORDER_COLOR}: var(${COLORS.GRAY_6});

      ${COLORS_FORM_GROUP.NUMBER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_FORM_GROUP.NUMBER_BG}: var(${COLORS.VIOLET_5});
      ${COLORS_FORM_GROUP.HINT_COLOR}: var(${COLORS.GRAY_4});

      ${COLORS_FORM_FIELD.HINT_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_FORM_FIELD.ERROR_COLOR}: var(${COLORS.RED_1});
      ${COLORS_FORM_FIELD.REQUIRED_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_FORM_FIELD.DESCRIPTION_COLOR}: var(${COLORS.GRAY_1});

      ${COLORS_TOAST.INFO_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TOAST.INFO_BG}: var(${COLORS.VIOLET_8});
      ${COLORS_TOAST.INFO_SECONDARY_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_TOAST.INFO_ICON_BG}: rgba(255, 255, 255, 0.1);
      ${COLORS_TOAST.INFO_ACTION_COLOR}: #cfcfcf;
      ${COLORS_TOAST.INFO_ACTION_HOVER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TOAST.ERROR_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TOAST.ERROR_BG}: var(${COLORS.RED_1});
      ${COLORS_TOAST.ERROR_SECONDARY_COLOR}: #f5f5f5;
      ${COLORS_TOAST.ERROR_ICON_BG}: rgba(255, 255, 255, 0.1);
      ${COLORS_TOAST.ERROR_ACTION_COLOR}: #ededed;
      ${COLORS_TOAST.ERROR_ACTION_HOVER_COLOR}: var(${COLORS.WHITE});

      ${COLORS_AVATAR.COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_AVATAR.BG}: var(${COLORS.GRAY_3});

      ${COLORS_SLIDER.BG}: var(${COLORS.VIOLET_5});
      ${COLORS_SLIDER.BG_HOVER}: var(${COLORS.VIOLET_6});
      ${COLORS_SLIDER.BG_ACTIVE}: var(${COLORS.VIOLET_7});
      ${COLORS_SLIDER.INACTIVE_BG}: var(${COLORS.GRAY_3});

      ${COLORS_LOGS_VIEW.BG}: var(${COLORS.GRAY_10});

      ${COLORS_TABLE.TABLE_ROW_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TABLE.TABLE_ROW_BACKGROUND}: var(${COLORS.GRAY_8});
      ${COLORS_TABLE.TABLE_ROW_ODD_BACKGROUND}: var(${COLORS.GRAY_7});
      ${COLORS_TABLE.TABLE_ROW_HOVER_SHADOW_LEFT}: var(${COLORS.VIOLET_5});
      ${COLORS_TABLE.TABLE_ROW_HOVER_SHADOW_TOP_BOTTOM}: #7373BF;
      ${COLORS_TABLE.TABLE_ROW_SELECTED_BACKGROUND}: var(${COLORS.VIOLET_8});
      ${COLORS_TABLE.TABLE_HEADER_BACKGROUND}: var(${COLORS.GRAY_7});
      ${COLORS_TABLE.TABLE_HEADER_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_TABLE.TABLE_HEADER_RESIZE_ICON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_TABLE.TABLE_FAVOURITE_ICON_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_TABLE.TABLE_FAVOURITE_ICON_HOVER_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_TABLE.TABLE_FAVOURITE_ICON_FILLED_COLOR}: var(${COLORS.YELLOW});
      ${COLORS_TABLE.TABLE_RADIO_ICON_DISABLED_COLOR}: var(${COLORS.GRAY_5});
      ${COLORS_TABLE.TABLE_HELP_ICON_COLOR}: #d2d2d2;
      ${COLORS_TABLE.TABLE_HELP_ICON_HOVER_COLOR}: var(${COLORS.WHITE});

      ${TABLE_BUTTON_COLORS.TEXT_ICON_CONTENT}: var(${COLORS.WHITE});
      ${TABLE_BUTTON_COLORS.TEXT_ICON_CONTENT_DISABLED}: var(${COLORS.GRAY_2});
      ${TABLE_BUTTON_COLORS.TEXT_ICON_BACKGROUND}: var(${COLORS.VIOLET_5});
      ${TABLE_BUTTON_COLORS.TEXT_ICON_BACKGROUND_DISABLED}: var(${COLORS.VIOLET_8});
      ${TABLE_BUTTON_COLORS.TEXT_ICON_BACKGROUND_HOVER}: var(${COLORS.VIOLET_6});
      ${TABLE_BUTTON_COLORS.TEXT_ICON_BACKGROUND_FOCUS}: var(${COLORS.VIOLET_6});
      ${TABLE_BUTTON_COLORS.TEXT_ICON_BACKGROUND_ACTIVE}: var(${COLORS.VIOLET_7});
      ${TABLE_BUTTON_COLORS.TEXT_ICON_BACKGROUND_IN_PROGRESS}: var(${COLORS.GRAY_3});

      ${TABLE_BUTTON_COLORS.ICON_CONTENT}: var(${COLORS.WHITE});
      ${TABLE_BUTTON_COLORS.ICON_CONTENT_DISABLED}: var(${COLORS.GRAY_2});
      ${TABLE_BUTTON_COLORS.ICON_BACKGROUND}: var(${COLORS.GRAY_4});
      ${TABLE_BUTTON_COLORS.ICON_BACKGROUND_DISABLED}: var(${COLORS.VIOLET_8});
      ${TABLE_BUTTON_COLORS.ICON_BACKGROUND_HOVER}: var(${COLORS.VIOLET_5});
      ${TABLE_BUTTON_COLORS.ICON_BACKGROUND_FOCUS}: var(${COLORS.VIOLET_5});
      ${TABLE_BUTTON_COLORS.ICON_BACKGROUND_ACTIVE}: var(${COLORS.VIOLET_6});
      ${TABLE_BUTTON_COLORS.ICON_BACKGROUND_IN_PROGRESS}: var(${COLORS.VIOLET_7});

      ${COLORS_FILTER.FILTER_BACKGROUND}: var(${COLORS.GRAY_8});
      ${COLORS_FILTER.FILTER_ACTION_BUTTON_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_FILTER.FILTER_ACTION_BUTTON_FILLED}: var(${COLORS.GRAY_3});
      ${COLORS_FILTER.FILTER_ACTION_BUTTON_HOVER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_FILTER.FILTER_ACTION_BUTTON_HOVER_FILLED}: var(${COLORS.WHITE});
      ${COLORS_FILTER.FILTER_ACTION_BUTTON_DISABLED_COLOR}: var(${COLORS.GRAY_5});
      ${COLORS_FILTER.FILTER_ACTION_BUTTON_DISABLED_FILLED}: #454545;

      ${COLORS_NO_DATA_PAGE.ICON_FILL}: var(${COLORS.VIOLET_5});
      ${COLORS_NO_DATA_PAGE.TITLE_COLOR}: var(${COLORS.WHITE});
      ${COLORS_NO_DATA_PAGE.CONTENT_COLOR}: var(${COLORS.GRAY_1});

      ${COLORS_ICON_BUTTON.POPUP_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_ICON_BUTTON.POPUP_COLOR_HOVER}: var(${COLORS.WHITE});
    }
  }
`;
