const GREY = {
  0: '--color-grey-0',
  50: '--color-grey-50',
  100: '--color-grey-100',
  150: '--color-grey-150',
  200: '--color-grey-200',
  250: '--color-grey-250',
  300: '--color-grey-300',
  350: '--color-grey-350',
  400: '--color-grey-400',
  450: '--color-grey-450',
  500: '--color-grey-500',
  550: '--color-grey-550',
  600: '--color-grey-600',
  650: '--color-grey-650',
  700: '--color-grey-700',
  750: '--color-grey-750',
  800: '--color-grey-800',
  850: '--color-grey-850',
  900: '--color-grey-900',
  1000: '--color-grey-1000',
};

const PURPLE = {
  10: '--color-purple-10',
  25: '--color-purple-25',
  50: '--color-purple-50',
  100: '--color-purple-100',
  115: '--color-purple-115',
  125: '--color-purple-125',
  150: '--color-purple-150',
};

const GREEN = {
  10: '--color-green-10',
  25: '--color-green-25',
  50: '--color-green-50',
  100: '--color-green-100',
  115: '--color-green-115',
  125: '--color-green-125',
  150: '--color-green-150',
};

const BLACK_ALFA = {
  8: '--color-black-alfa-8',
  16: '--color-black-alfa-16',
  24: '--color-black-alfa-24',
  48: '--color-black-alfa-48',
};

const WHITE_ALFA = {
  8: '--color-white-alfa-8',
  16: '--color-white-alfa-16',
  24: '--color-white-alfa-24',
  48: '--color-white-alfa-48',
};

const BLUE_GREY = {
  40: '--color-blue-grey-40',
  50: '--color-blue-grey-50',
  60: '--color-blue-grey-60',
  70: '--color-blue-grey-70',
  80: '--color-blue-grey-80',
  90: '--color-blue-grey-90',
  100: '--color-blue-grey-100',
};

const PRESET = {
  GREEN_LIGHT: '--color-green-light',
  GREEN_DARK: '--color-green-dark',
  YELLOW_LIGHT: '--color-yellow-light',
  YELLOW_DARK: '--color-yellow-dark',
  SILVER_GRAY_LIGHT: '--color-silver-gray-light',
  SILVER_GRAY_DARK: '--color-silver-gray-dark',
  CHARCOAL_GRAY_LIGHT: '--color-charcoal-gray-light',
  CHARCOAL_GRAY_DARK: '--color-charcoal-gray-dark',
  ORANGE_LIGHT: '--color-orange-light',
  ORANGE_DARK: '--color-orange-dark',
  RED_LIGHT: '--color-red-light',
  RED_DARK: '--color-red-dark',
  PINK_LIGHT: '--color-pink-light',
  PINK_DARK: '--color-pink-dark',
  VIOLET_LIGHT: '--color-violet-light',
  VIOLET_DARK: '--color-violet-dark',
  BLUE_LIGHT: '--color-blue-light',
  BLUE_DARK: '--color-blue-dark',
  BROWN_LIGHT: '--color-brown-light',
  BROWN_DARK: '--color-brown-dark',
  GRASS_LIGHT: '--color-grass-light',
  GRASS_DARK: '--color-grass-dark',
  SEAMOUNT_LIGHT: '--color-seamount-light',
  SEAMOUNT_DARK: '--color-seamount-dark',
  SUNNY_YELLOW: '--color-sunny-yellow',
  EMERALD_GREEN: '--color-emerald-green',
  BERRY_RED_1: '--color-berry-red-1',
  BERRY_RED_2: '--color-berry-red-2',
  BERRY_RED_3: '--color-berry-red-3',
  GRACE_1: '--color-grace-1',
  GRACE_1_ALPHA: '--color-grace-alpha-1',
  GRACE_2: '--color-grace-2',
  GRACE_2_ALPHA: '--color-grace-alpha-2',
  GRACE_3: '--color-grace-3',
  GRACE_3_ALPHA: '--color-grace-alpha-3',
  GRACE_4: '--color-grace-4',
  GRACE_4_ALPHA: '--color-grace-alpha-4',
  GRACE_5: '--color-grace-5',
  GRACE_5_ALPHA: '--color-grace-alpha-5',
  GRACE_6: '--color-grace-6',
  GRACE_6_ALPHA: '--color-grace-alpha-6',
  GRACE_7: '--color-grace-7',
  GRACE_7_ALPHA: '--color-grace-alpha-7',
  GRACE_8: '--color-grace-8',
  GRACE_8_ALPHA: '--color-grace-alpha-8',
  GRACE_9: '--color-grace-9',
  GRACE_9_ALPHA: '--color-grace-alpha-9',
  GRACE_10: '--color-grace-10',
  GRACE_10_ALPHA: '--color-grace-alpha-10',
  GRACE_11: '--color-grace-11',
  GRACE_11_ALPHA: '--color-grace-alpha-11',
  GRACE_12: '--color-grace-12',
  GRACE_12_ALPHA: '--color-grace-alpha-12',
  GRACE_13: '--color-grace-13',
  GRACE_13_ALPHA: '--color-grace-alpha-13',
  GRACE_14: '--color-grace-14',
  GRACE_14_ALPHA: '--color-grace-alpha-14',
  GRACE_15: '--color-grace-15',
  GRACE_15_ALPHA: '--color-grace-alpha-15',
  GRACE_16: '--color-grace-16',
  GRACE_16_ALPHA: '--color-grace-alpha-16',
  GRADIENT_1: '--color-gradient-1',
  GRADIENT_2: '--color-gradient-2',
  GRADIENT_3: '--color-gradient-3',
  GRADIENT_4: '--color-gradient-4',
};

export { GREY, PURPLE, GREEN, BLACK_ALFA, WHITE_ALFA, BLUE_GREY, PRESET };

export default {
  GREY,
  PURPLE,
  GREEN,
  BLACK_ALFA,
  WHITE_ALFA,
  BLUE_GREY,
  PRESET,
};
