import { css } from '@linaria/core';

import {
  COLORS,
  COLORS_BRAND,
  COLORS_GENERAL,
  COLORS_BUTTON,
  COLORS_TAG,
} from './vars';

export const green = css`
  :global() {
    [data-theme='green'] {
      ${COLORS_BRAND.GREEN}: #07E897;
      ${COLORS_BRAND.GREEN_GRADIENT}: linear-gradient(235.56deg, #07E897 40.45%, #00956F 90.43%);
      ${COLORS_BRAND.BLACK}: #343F48;
      ${COLORS_BRAND.GRAY}: #D2D2D2;

      ${COLORS.GRAY_1}: #f5f5f5;
      ${COLORS.GRAY_2}: #ededed;
      ${COLORS.GRAY_3}: #d2d2d2;
      ${COLORS.GRAY_4}: #cfcfcf;
      ${COLORS.GRAY_5}: #cccccc;
      ${COLORS.GRAY_6}: #a0a0a0;
      ${COLORS.GRAY_7}: #6c6c6c;
      ${COLORS.BLACK_1}: #1b1b1b;
      ${COLORS.BLACK_2}: #343f48;
      ${COLORS.WHITE}: #ffffff;
      ${COLORS.GREEN_1}: #E8FFF7;
      ${COLORS.GREEN_2}: #B2FFE4;
      ${COLORS.GREEN_3}: #67FBC6;
      ${COLORS.GREEN_4}: #00EA95;
      ${COLORS.GREEN_5}: #07E897;
      ${COLORS.GREEN_6}: #07D88D;
      ${COLORS.GREEN_7}: #07CC85;
      ${COLORS.GREEN_8}: #12BBA6;
      ${COLORS.BLUE_1}: #258CB8;
      ${COLORS.BLUE_2}: #375EC9;
      ${COLORS.PURPLE}: #5c00ec;
      ${COLORS.RED_1}: #e84e58;
      ${COLORS.RED_2}: #ff0000;
      ${COLORS.YELLOW}: #F0D559;

      ${COLORS_TAG.RED}: #FBD6D5;
      ${COLORS_TAG.PINK}: #F5D5E5;
      ${COLORS_TAG.PURPLE}: #DFD7F7;
      ${COLORS_TAG.BLUE}: #D5E4F7;
      ${COLORS_TAG.GREEN}: #D7E7E2;
      ${COLORS_TAG.YELLOW}: #F9EED8;
      ${COLORS_TAG.ORANGE}: #FAE1D5;
      ${COLORS_TAG.BROWN}: #E6D6D0;
      ${COLORS_TAG.GRAY_1}: #E6E6E5;
      ${COLORS_TAG.GRAY_2}: #D7D7D6;

      ${COLORS_GENERAL.BACKGROUND}: var(${COLORS.GRAY_2});
      ${COLORS_GENERAL.TEXT}: var(${COLORS.BLACK_2});

      ${COLORS_BUTTON.FOCUS_SHADOW}: var(${COLORS.GREEN_3});

      ${COLORS_BUTTON.FILLED_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.FILLED_ICON_COLOR}: var(${COLORS.GREEN_5});
      ${COLORS_BUTTON.FILLED_BG}: var(${COLORS.BLACK_2});
      ${COLORS_BUTTON.FILLED_HOVER_BG}: #282D30;
      ${COLORS_BUTTON.FILLED_ACTIVE_BG}: var(${COLORS.BLACK_1});
      ${COLORS_BUTTON.FILLED_DISABLED_COLOR}: var(${COLORS.GRAY_6});
      ${COLORS_BUTTON.FILLED_DISABLED_BG}: var(${COLORS.BLACK_2});
      ${COLORS_BUTTON.FILLED_FOCUS_BG}: #282D30;

      ${COLORS_BUTTON.OUTLINED_COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_BUTTON.OUTLINED_BORDER}: var(${COLORS.GREEN_5});
      ${COLORS_BUTTON.OUTLINED_HOVER_COLOR}: var(${COLORS.GREEN_6});
      ${COLORS_BUTTON.OUTLINED_HOVER_BORDER}: var(${COLORS.GREEN_6});
      ${COLORS_BUTTON.OUTLINED_ACTIVE_COLOR}: var(${COLORS.GREEN_7});
      ${COLORS_BUTTON.OUTLINED_ACTIVE_BORDER}: var(${COLORS.GREEN_7});
      ${COLORS_BUTTON.OUTLINED_DISABLED_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_BUTTON.OUTLINED_DISABLED_BORDER}: var(${COLORS.GRAY_2});
      ${COLORS_BUTTON.OUTLINED_FOCUS_COLOR}: var(${COLORS.GREEN_6});
      ${COLORS_BUTTON.OUTLINED_FOCUS_BORDER}: var(${COLORS.GREEN_6});

      ${COLORS_BUTTON.TRANSPARENT_COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_BUTTON.TRANSPARENT_HOVER_BG}: var(${COLORS.GRAY_1});
      ${COLORS_BUTTON.TRANSPARENT_HOVER_COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_BUTTON.TRANSPARENT_ACTIVE_BG}: var(${COLORS.GRAY_2});
      ${COLORS_BUTTON.TRANSPARENT_ACTIVE_COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_BUTTON.TRANSPARENT_DISABLED_COLOR}: #C6C6C6;
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_BG}: var(${COLORS.GRAY_1});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_BORDER}: transparent;

      ${COLORS_BUTTON.FILLED_GREEN_COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_BUTTON.FILLED_GREEN_BG}: var(${COLORS.GREEN_5});
      ${COLORS_BUTTON.FILLED_GREEN_HOVER_BG}: var(${COLORS.GREEN_6});
      ${COLORS_BUTTON.FILLED_GREEN_ACTIVE_BG}: var(${COLORS.GREEN_7});
      ${COLORS_BUTTON.FILLED_GREEN_DISABLED_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_BUTTON.FILLED_GREEN_DISABLED_BG}: var(${COLORS.GRAY_2});
      ${COLORS_BUTTON.FILLED_GREEN_FOCUS_BG}: var(${COLORS.GREEN_6});

      ${COLORS_BUTTON.WHITE_COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_BUTTON.WHITE_BG}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.WHITE_HOVER_COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_BUTTON.WHITE_HOVER_BG}: var(${COLORS.GREEN_6});
      ${COLORS_BUTTON.WHITE_ACTIVE_COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_BUTTON.WHITE_ACTIVE_BG}: var(${COLORS.GREEN_7});
      ${COLORS_BUTTON.WHITE_DISABLED_COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_BUTTON.WHITE_DISABLED_BG}: var(${COLORS.GRAY_3});
      ${COLORS_BUTTON.WHITE_FOCUS_COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_BUTTON.WHITE_FOCUS_BG}: var(${COLORS.GREEN_6});
      ${COLORS_BUTTON.WHITE_FOCUS_OUTLINE}: var(${COLORS.GREEN_3});
      ${COLORS_BUTTON.WHITE_FOCUS_BORDER}: transparent;
    }
  }
`;
