import { css } from '@linaria/core';

import {
  COLORS,
  COLORS_BRAND,
  COLORS_GENERAL,
  COLORS_BUTTON,
  COLORS_TAG,
  COLORS_STATUS,
  COLORS_SWITCH,
  COLORS_TOOLTIP,
  COLORS_FORM_GROUP,
  COLORS_FORM_FIELD,
  COLORS_DRAWER,
  COLORS_TOAST,
} from './vars';

export const greenDark = css`
  :global() {
    [data-theme='greenDark'] {
      ${COLORS_BRAND.GREEN}: #07E897;
      ${COLORS_BRAND.GREEN_GRADIENT}: linear-gradient(235.56deg, #07E897 40.45%, #00956F 90.43%);
      ${COLORS_BRAND.BLACK}: #343F48;
      ${COLORS_BRAND.GRAY}: #D2D2D2;

      ${COLORS.GRAY_1}: #C6C6C6;
      ${COLORS.GRAY_2}: #989EA3;
      ${COLORS.GRAY_3}: #858A8F;
      ${COLORS.GRAY_4}: #636773;
      ${COLORS.GRAY_5}: #45474D;
      ${COLORS.GRAY_6}: #454545;
      ${COLORS.GRAY_7}: #3C3D41;
      ${COLORS.GRAY_8}: #323538;
      ${COLORS.GRAY_9}: #272829;
      ${COLORS.GRAY_10}: #252525;
      ${COLORS.GRAY_11}: #171717;
      ${COLORS.WHITE}: #ffffff;
      ${COLORS.GREEN_1}: #67FBC6;
      ${COLORS.GREEN_2}: #00EA95;
      ${COLORS.GREEN_3}: #07E897;
      ${COLORS.GREEN_4}: #07D88D;
      ${COLORS.GREEN_5}: #07CC85;
      ${COLORS.GREEN_6}: #12BBA6;
      ${COLORS.GREEN_7}: #157552;
      ${COLORS.BLUE_1}: #258CB8;
      ${COLORS.BLUE_2}: #375EC9;
      ${COLORS.PURPLE}: #5C00EC;
      ${COLORS.RED_1}: #E84E58;
      ${COLORS.RED_2}: #FF0000;
      ${COLORS.YELLOW}: #F0D559;

      ${COLORS_TAG.RED}: #98605B;
      ${COLORS_TAG.PINK}: #8A5273;
      ${COLORS_TAG.PURPLE}: #6A5B8C;
      ${COLORS_TAG.BLUE}: #517086;
      ${COLORS_TAG.GREEN}: #527771;
      ${COLORS_TAG.YELLOW}: #9E9056;
      ${COLORS_TAG.ORANGE}: #9A754F;
      ${COLORS_TAG.BROWN}: #685C56;
      ${COLORS_TAG.GRAY_1}: #6C6F71;
      ${COLORS_TAG.GRAY_2}: #515558;

      ${COLORS_GENERAL.BACKGROUND}: var(${COLORS.GRAY_11});
      ${COLORS_GENERAL.TEXT}: var(${COLORS_BRAND.GRAY});

      ${COLORS_BUTTON.FOCUS_SHADOW}: var(${COLORS.GREEN_7});

      ${COLORS_BUTTON.FILLED_COLOR}: var(${COLORS_BRAND.BLACK});
      ${COLORS_BUTTON.FILLED_ICON_COLOR}: var(${COLORS_BRAND.BLACK});
      ${COLORS_BUTTON.FILLED_BG}: var(${COLORS.GREEN_3});
      ${COLORS_BUTTON.FILLED_HOVER_BG}: var(${COLORS.GREEN_4});
      ${COLORS_BUTTON.FILLED_ACTIVE_BG}: var(${COLORS.GREEN_5});
      ${COLORS_BUTTON.FILLED_DISABLED_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_BUTTON.FILLED_DISABLED_BG}: var(${COLORS.GRAY_7});
      ${COLORS_BUTTON.FILLED_FOCUS_BG}: var(${COLORS.GREEN_4});

      ${COLORS_BUTTON.OUTLINED_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.OUTLINED_BORDER}: var(${COLORS.GREEN_3});
      ${COLORS_BUTTON.OUTLINED_HOVER_COLOR}: var(${COLORS.GREEN_4});
      ${COLORS_BUTTON.OUTLINED_HOVER_BORDER}: var(${COLORS.GREEN_4});
      ${COLORS_BUTTON.OUTLINED_ACTIVE_COLOR}: var(${COLORS.GREEN_5});
      ${COLORS_BUTTON.OUTLINED_ACTIVE_BORDER}: var(${COLORS.GREEN_5});
      ${COLORS_BUTTON.OUTLINED_DISABLED_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_BUTTON.OUTLINED_DISABLED_BORDER}: var(${COLORS.GRAY_4});
      ${COLORS_BUTTON.OUTLINED_FOCUS_COLOR}: var(${COLORS.GREEN_4});
      ${COLORS_BUTTON.OUTLINED_FOCUS_BORDER}: var(${COLORS.GREEN_4});

      ${COLORS_BUTTON.TRANSPARENT_COLOR}: var(${COLORS.GREEN_3});
      ${COLORS_BUTTON.TRANSPARENT_HOVER_BG}: var(${COLORS.GRAY_7});
      ${COLORS_BUTTON.TRANSPARENT_HOVER_COLOR}: var(${COLORS.GREEN_4});
      ${COLORS_BUTTON.TRANSPARENT_ACTIVE_BG}: var(${COLORS.GRAY_7});
      ${COLORS_BUTTON.TRANSPARENT_ACTIVE_COLOR}: var(${COLORS.GREEN_5});
      ${COLORS_BUTTON.TRANSPARENT_DISABLED_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_COLOR}: var(${COLORS.GREEN_4});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_BG}: var(${COLORS.GRAY_5});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_BORDER}: transparent;

      ${COLORS_BUTTON.TABLE_MENU_BUTTON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_BUTTON.TABLE_MENU_BUTTON_HOVER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.TABLE_MENU_BUTTON_DISABLED_COLOR}: #454545;
      ${COLORS_BUTTON.TABLE_MENU_BUTTON_ACTIVE_COLOR}: #a0a0a0;

      ${COLORS_BUTTON.FILLED_BRAND_COLOR}: #343f48;
      ${COLORS_BUTTON.FILLED_BRAND_BG}: #07e897;
      ${COLORS_BUTTON.FILLED_BRAND_HOVER_BG}: #07d88d;
      ${COLORS_BUTTON.FILLED_BRAND_ACTIVE_BG}: #07cc85;
      ${COLORS_BUTTON.FILLED_BRAND_DISABLED_COLOR}: #cfcfcf;
      ${COLORS_BUTTON.FILLED_BRAND_DISABLED_BG}: #ededed;
      ${COLORS_BUTTON.FILLED_BRAND_FOCUS_BG}: #07d88d;

      ${COLORS_BUTTON.WHITE_COLOR}: #282D30;
      ${COLORS_BUTTON.WHITE_BG}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.WHITE_HOVER_COLOR}: var(${COLORS.GREEN_4});
      ${COLORS_BUTTON.WHITE_HOVER_BG}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.WHITE_ACTIVE_COLOR}: var(${COLORS.GREEN_5});
      ${COLORS_BUTTON.WHITE_ACTIVE_BG}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.WHITE_DISABLED_COLOR}: #63677380;
      ${COLORS_BUTTON.WHITE_DISABLED_BG}: #ffffff80;
      ${COLORS_BUTTON.WHITE_FOCUS_COLOR}: var(${COLORS.GREEN_4});
      ${COLORS_BUTTON.WHITE_FOCUS_BG}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.WHITE_FOCUS_OUTLINE}: var(${COLORS.GREEN_7});
      ${COLORS_BUTTON.WHITE_FOCUS_BORDER}: transparent;

      ${COLORS_STATUS.COLOR}: var(${COLORS.GRAY_1});
      ${COLORS_STATUS.FAILED_BG}: var(${COLORS.RED_2});
      ${COLORS_STATUS.SUCCESS_BG}: var(${COLORS.GREEN_3});
      ${COLORS_STATUS.WARNING_BG}: var(${COLORS.YELLOW});
      ${COLORS_STATUS.UNACTIVE_BG}: var(${COLORS.GRAY_3});

      ${COLORS_SWITCH.UNACTIVE_BG}: var(${COLORS.GRAY_3});
      ${COLORS_SWITCH.UNACTIVE_HOVER_BG}: var(${COLORS.GRAY_4});
      ${COLORS_SWITCH.UNACTIVE_DISABLED_BG}: var(${COLORS.GRAY_5});
      ${COLORS_SWITCH.ACTIVE_BG}: var(${COLORS.GREEN_3});
      ${COLORS_SWITCH.ACTIVE_HOVER_BG}: var(${COLORS.GREEN_4});
      ${COLORS_SWITCH.ACTIVE_DISABLED_BG}: var(${COLORS.GREEN_7});

      ${COLORS_TOOLTIP.CONTAINER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TOOLTIP.CONTAINER_BG}: var(${COLORS_BRAND.BLACK});
      ${COLORS_TOOLTIP.ICON_FILL}: var(${COLORS_BRAND.GRAY});
      ${COLORS_TOOLTIP.ICON_HOVER_FILL}: var(${COLORS.WHITE});
      ${COLORS_TOOLTIP.MENU_BG}: var(${COLORS.GRAY_8});
      ${COLORS_TOOLTIP.MENU_ITEM_HOVER_BG}: var(${COLORS.GRAY_7});

      ${COLORS_FORM_GROUP.NUMBER_COLOR}: var(${COLORS_BRAND.BLACK});
      ${COLORS_FORM_GROUP.NUMBER_BG}: var(${COLORS.GREEN_3});
      ${COLORS_FORM_GROUP.HINT_COLOR}: var(${COLORS.GRAY_4});

      ${COLORS_FORM_FIELD.HINT_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_FORM_FIELD.ERROR_COLOR}: var(${COLORS.RED_1});

      ${COLORS_DRAWER.BG}: var(${COLORS.GRAY_9});

      ${COLORS_TOAST.INFO_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TOAST.INFO_BG}: var(${COLORS.GRAY_5});
      ${COLORS_TOAST.INFO_SECONDARY_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_TOAST.INFO_ICON_BG}: rgba(255, 255, 255, 0.1);
      ${COLORS_TOAST.INFO_ACTION_COLOR}: #cfcfcf;
      ${COLORS_TOAST.INFO_ACTION_HOVER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TOAST.ERROR_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TOAST.ERROR_BG}: var(${COLORS.RED_1});
      ${COLORS_TOAST.ERROR_SECONDARY_COLOR}: #f5f5f5;
      ${COLORS_TOAST.ERROR_ICON_BG}: rgba(255, 255, 255, 0.1);
      ${COLORS_TOAST.ERROR_ACTION_COLOR}: #ededed;
      ${COLORS_TOAST.ERROR_ACTION_HOVER_COLOR}: var(${COLORS.WHITE});
    }
  }
`;
