import { css } from '@linaria/core';

import {
  COLORS,
  COLORS_GENERAL,
  COLORS_BUTTON,
  COLORS_ICON,
  COLORS_DIVIDER,
  COLORS_SPIN,
  COLORS_MODAL,
  COLORS_TOOLTIP,
} from './vars';

export const purple = css`
  :global() {
    [data-theme='purple'] {
      ${COLORS.GRAY_1}: #f5f5f5;
      ${COLORS.GRAY_2}: #ededed;
      ${COLORS.GRAY_3}: #d2d2d2;
      ${COLORS.GRAY_4}: #cfcfcf;
      ${COLORS.GRAY_5}: #cccccc;
      ${COLORS.GRAY_6}: #a0a0a0;
      ${COLORS.GRAY_7}: #6c6c6c;
      ${COLORS.BLACK_1}: #1b1b1b;
      ${COLORS.BLACK_2}: #343f48;
      ${COLORS.WHITE}: #ffffff;
      ${COLORS.VIOLET_1}: #f3f3fe;
      ${COLORS.VIOLET_2}: #e5e6fe;
      ${COLORS.VIOLET_3}: #bcbced;
      ${COLORS.VIOLET_4}: #aaabfc;
      ${COLORS.VIOLET_5}: #5558fa;
      ${COLORS.VIOLET_6}: #484bd5;
      ${COLORS.VIOLET_7}: #4042bc;
      ${COLORS.PURPLE}: #5c00ec;
      ${COLORS.GREEN_1}: #00ea95;
      ${COLORS.GREEN_2}: #07e897;
      ${COLORS.GREEN_3}: #12bba6;
      ${COLORS.BLUE_1}: #258CB8;
      ${COLORS.BLUE_2}: #375EC9;
      ${COLORS.RED_1}: #e84e58;
      ${COLORS.RED_2}: #ff0000;
      ${COLORS.YELLOW}: #F0D559;

      ${COLORS_GENERAL.BACKGROUND}: var(${COLORS.GRAY_2});
      ${COLORS_GENERAL.TEXT}: var(${COLORS.BLACK_2});

      ${COLORS_BUTTON.FOCUS_SHADOW}: var(${COLORS.VIOLET_2});

      ${COLORS_BUTTON.FILLED_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.FILLED_BG}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.FILLED_HOVER_BG}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.FILLED_ACTIVE_BG}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.FILLED_DISABLED_COLOR}: var(${COLORS.VIOLET_2});
      ${COLORS_BUTTON.FILLED_DISABLED_BG}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.FILLED_FOCUS_BG}: var(${COLORS.VIOLET_6});

      ${COLORS_BUTTON.OUTLINED_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.OUTLINED_BORDER}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.OUTLINED_HOVER_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.OUTLINED_HOVER_BORDER}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.OUTLINED_ACTIVE_COLOR}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.OUTLINED_DISABLED_COLOR}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.OUTLINED_FOCUS_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.OUTLINED_FOCUS_BORDER}: var(${COLORS.VIOLET_6});

      ${COLORS_BUTTON.TRANSPARENT_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.TRANSPARENT_HOVER_BG}: var(${COLORS.VIOLET_1});
      ${COLORS_BUTTON.TRANSPARENT_HOVER_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.TRANSPARENT_ACTIVE_BG}: var(${COLORS.VIOLET_2});
      ${COLORS_BUTTON.TRANSPARENT_ACTIVE_COLOR}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.TRANSPARENT_DISABLED_COLOR}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_BG}: var(${COLORS.VIOLET_1});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_BORDER}: var(${COLORS.VIOLET_6});

      ${COLORS_BUTTON.WHITE_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.WHITE_BG}: var(${COLORS.BLACK_1});
      ${COLORS_BUTTON.WHITE_HOVER_BG}: var(${COLORS.VIOLET_2});
      ${COLORS_BUTTON.WHITE_HOVER_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.WHITE_ACTIVE_BG}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.WHITE_ACTIVE_COLOR}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.WHITE_DISABLED_COLOR}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.WHITE_DISABLED_BG}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.WHITE_FOCUS_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.WHITE_FOCUS_BG}: var(${COLORS.VIOLET_2});
      ${COLORS_BUTTON.WHITE_FOCUS_OUTLINE}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.WHITE_FOCUS_BORDER}: transparent;

      ${COLORS_ICON.FILL}: var(${COLORS.GRAY_3});
      ${COLORS_ICON.HOVER_FILL}: var(${COLORS.VIOLET_5});
      ${COLORS_ICON.ACTIVE_FILL}: var(${COLORS.GRAY_2});

      ${COLORS_DIVIDER.COLOR_LIGHT}: var(${COLORS.GRAY_2});
      ${COLORS_DIVIDER.COLOR_MIDDLE}: #e4e4e4;
      ${COLORS_DIVIDER.COLOR_DARK}: var(${COLORS.BLACK_2});

      ${COLORS_SPIN.BORDER}: var(${COLORS.GRAY_3});
      ${COLORS_SPIN.BORDER_TOP}: var(${COLORS.GRAY_1});
      ${COLORS_SPIN.TEXT_COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_SPIN.BORDER_REV}: var(${COLORS.WHITE});
      ${COLORS_SPIN.BORDER_REV_TOP}: #ffffff33;
      ${COLORS_SPIN.TEXT_REV_COLOR}: var(${COLORS.WHITE});

      ${COLORS_MODAL.BG}: var(${COLORS.WHITE});
      ${COLORS_MODAL.TITLE_COLOR}: var(${COLORS.BLACK_1 });
      ${COLORS_MODAL.DESCRIPTION_COLOR}: var(${COLORS.GRAY_7});

      ${COLORS_TOOLTIP.CONTAINER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TOOLTIP.CONTAINER_BG}: var(${COLORS.BLACK_2});
      ${COLORS_TOOLTIP.MENU_BG}: var(${COLORS.WHITE});
      ${COLORS_TOOLTIP.MENU_ITEM_HOVER_BG}: var(${COLORS.GRAY_2});
      ${COLORS_TOOLTIP.ICON_FILL}: var(${COLORS.GRAY_3});
      ${COLORS_TOOLTIP.ICON_HOVER_FILL}: var(${COLORS.WHITE});
      ${COLORS_TOOLTIP.ICON_ACTIVE_FILL}: var(${COLORS.GRAY_1});
    }
  }
`;
