import { css } from '@linaria/core';

import {
  COLORS,
  COLORS_GENERAL,
  COLORS_BUTTON,
  COLORS_ICON,
  COLORS_DIVIDER,
  COLORS_SPIN,
  COLORS_MODAL,
  COLORS_TOOLTIP,
  COLORS_TAG,
  COLORS_INPUT,
  COLORS_RADIO,
  COLORS_SELECT,
} from './vars';

export const purpleDark = css`
  :global() {
    [data-theme='purpleDark'] {
      ${COLORS.GRAY_1}: #c6c6c6;
      ${COLORS.GRAY_2}: #a0a0a0;
      ${COLORS.GRAY_3}: #898989;
      ${COLORS.GRAY_4}: #838383;
      ${COLORS.GRAY_5}: #6d6d6d;
      ${COLORS.GRAY_6}: #484848;
      ${COLORS.GRAY_7}: #414141;
      ${COLORS.GRAY_8}: #313131;
      ${COLORS.BLACK_1}: #252525;
      ${COLORS.BLACK_2}: #171717;
      ${COLORS.WHITE}: #ffffff;
      ${COLORS.VIOLET_1}: #f3f3f3;
      ${COLORS.VIOLET_2}: #e5e6fe;
      ${COLORS.VIOLET_3}: #aaabfc;
      ${COLORS.VIOLET_4}: #a9abff;
      ${COLORS.VIOLET_5}: #5558fa;
      ${COLORS.VIOLET_6}: #484bd5;
      ${COLORS.VIOLET_7}: #4042bc;
      ${COLORS.VIOLET_8}: #2f3065;
      ${COLORS.PURPLE}: #5C00EC;
      ${COLORS.GREEN_1}: #12bba6;
      ${COLORS.GREEN_2}: #00ea95;
      ${COLORS.GREEN_3}: #07e897;
      ${COLORS.BLUE_1}: #375EC9;
      ${COLORS.BLUE_2}: #258CB8;
      ${COLORS.RED_1}: #e84e58;
      ${COLORS.RED_2}: #ff0000;
      ${COLORS.YELLOW}: #F0D559;

      ${COLORS_GENERAL.BACKGROUND}: var(${COLORS.BLACK_2});
      ${COLORS_GENERAL.TEXT}: var(${COLORS.GRAY_1});

      ${COLORS_BUTTON.FOCUS_SHADOW}: var(${COLORS.VIOLET_8});

      ${COLORS_BUTTON.FILLED_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.FILLED_BG}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.FILLED_HOVER_BG}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.FILLED_ACTIVE_BG}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.FILLED_DISABLED_COLOR}: var(${COLORS.GRAY_5});
      ${COLORS_BUTTON.FILLED_DISABLED_BG}: var(${COLORS.VIOLET_8});
      ${COLORS_BUTTON.FILLED_FOCUS_BG}: var(${COLORS.VIOLET_6});

      ${COLORS_BUTTON.OUTLINED_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.OUTLINED_BORDER}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.OUTLINED_HOVER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.OUTLINED_HOVER_BORDER}: var(${COLORS.VIOLET_3});
      ${COLORS_BUTTON.OUTLINED_ACTIVE_COLOR}: var(${COLORS.VIOLET_3});
      ${COLORS_BUTTON.OUTLINED_DISABLED_COLOR}: #aaabfc4d;
      ${COLORS_BUTTON.OUTLINED_FOCUS_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.OUTLINED_FOCUS_BORDER}: var(${COLORS.VIOLET_5});

      ${COLORS_BUTTON.TRANSPARENT_COLOR}: var(${COLORS.VIOLET_3});
      ${COLORS_BUTTON.TRANSPARENT_HOVER_BG}: var(${COLORS.GRAY_8});
      ${COLORS_BUTTON.TRANSPARENT_HOVER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.TRANSPARENT_ACTIVE_BG}: var(${COLORS.BLACK_1});
      ${COLORS_BUTTON.TRANSPARENT_ACTIVE_COLOR}: var(${COLORS.VIOLET_3});
      ${COLORS_BUTTON.TRANSPARENT_DISABLED_COLOR}: var(${COLORS.GRAY_5});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_BG}: var(${COLORS.GRAY_8});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_BORDER}: var(${COLORS.VIOLET_6});

      ${COLORS_BUTTON.WHITE_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.WHITE_BG}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.WHITE_HOVER_BG}: var(${COLORS.VIOLET_2});
      ${COLORS_BUTTON.WHITE_HOVER_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.WHITE_ACTIVE_BG}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.WHITE_ACTIVE_COLOR}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.WHITE_DISABLED_COLOR}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.WHITE_DISABLED_BG}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.WHITE_FOCUS_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.WHITE_FOCUS_BG}: var(${COLORS.VIOLET_2});
      ${COLORS_BUTTON.WHITE_FOCUS_OUTLINE}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.WHITE_FOCUS_BORDER}: var(${COLORS.VIOLET_6});

      ${COLORS_ICON.FILL}: var(${COLORS.GRAY_3});
      ${COLORS_ICON.HOVER_FILL}: var(${COLORS.VIOLET_5});
      ${COLORS_ICON.ACTIVE_FILL}: var(${COLORS.GRAY_2});

      ${COLORS_DIVIDER.COLOR_LIGHT}: var(${COLORS.BLACK_1});
      ${COLORS_DIVIDER.COLOR_MIDDLE}: var(${COLORS.GRAY_8});
      ${COLORS_DIVIDER.COLOR_DARK}: var(${COLORS.GRAY_6});

      ${COLORS_SPIN.BORDER}: var(${COLORS.WHITE});
      ${COLORS_SPIN.BORDER_TOP}: #ffffff33;
      ${COLORS_SPIN.TEXT_COLOR}: var(${COLORS.WHITE});

      ${COLORS_SPIN.BORDER_REV}: var(${COLORS.GRAY_3});
      ${COLORS_SPIN.BORDER_REV_TOP}: var(${COLORS.GRAY_1});
      ${COLORS_SPIN.TEXT_REV_COLOR}: var(${COLORS.BLACK_2});

      ${COLORS_MODAL.BG}: var(${COLORS.GRAY_8});
      ${COLORS_MODAL.TITLE_COLOR}: var(${COLORS.WHITE});
      ${COLORS_MODAL.DESCRIPTION_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_MODAL.PREVIEW_BG}: var(${COLORS.GRAY_8});
      ${COLORS_MODAL.PREVIEW_CLOSE_ICON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_MODAL.PREVIEW_CLOSE_ICON_HOVER_COLOR}: var(${COLORS.WHITE});

      ${COLORS_TOOLTIP.CONTAINER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TOOLTIP.CONTAINER_BG}: var(${COLORS.VIOLET_5});
      ${COLORS_TOOLTIP.MENU_BG}: var(${COLORS.GRAY_8});
      ${COLORS_TOOLTIP.MENU_ITEM_HOVER_BG}: var(${COLORS.GRAY_7});
      ${COLORS_TOOLTIP.ICON_FILL}: var(${COLORS.VIOLET_3});
      ${COLORS_TOOLTIP.ICON_HOVER_FILL}: var(${COLORS.WHITE});
      ${COLORS_TOOLTIP.ICON_ACTIVE_FILL}: var(${COLORS.VIOLET_3});

      ${COLORS_TAG.TAG_TEXT_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TAG.TAG_BG_GREEN}: #527771;
      ${COLORS_TAG.TAG_BG_BLUE}: #517086;
      ${COLORS_TAG.TAG_BG_PURPLE}: #6a5b8c;
      ${COLORS_TAG.TAG_BG_PINK}: #8a5273;
      ${COLORS_TAG.TAG_BG_RED}: #98605b;
      ${COLORS_TAG.TAG_BG_GRAY_DEFAULT}: #6c6f71;
      ${COLORS_TAG.TAG_BG_GRAY}: #515558;
      ${COLORS_TAG.TAG_BG_BROWN}: #685c56;
      ${COLORS_TAG.TAG_BG_ORANGE}: #9a754f;
      ${COLORS_TAG.TAG_BG_YELLOW}: #9e9056;

      ${COLORS_INPUT.INPUT_BG}: var(${COLORS.GRAY_8});
      ${COLORS_INPUT.INPUT_BORDER}: var(${COLORS.GRAY_7});
      ${COLORS_INPUT.INPUT_PLACEHOLDER_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_INPUT.INPUT_TEXT_COLOR}: var(${COLORS.WHITE});
      ${COLORS_INPUT.INPUT_FOCUS_BORDER}: var(${COLORS.GRAY_3});
      ${COLORS_INPUT.INPUT_FOCUS_BACKGROUND}: var(${COLORS.GRAY_7});
      ${COLORS_INPUT.INPUT_HOVER_BORDER}: var(${COLORS.GRAY_6});
      ${COLORS_INPUT.INPUT_HOVER_PLACEHOLDER_COLOR}: var(${COLORS.GRAY_1});
      ${COLORS_INPUT.INPUT_HOVER_BACKGROUND}: var(${COLORS.GRAY_7});
      ${COLORS_INPUT.INPUT_ERROR}: var(${COLORS.RED_1});
      ${COLORS_INPUT.INPUT_DISABLED_BACKGROUND}: var(${COLORS.BLACK_1});
      ${COLORS_INPUT.INPUT_DISABLED_COLOR}: var(${COLORS.GRAY_5});
      ${COLORS_INPUT.INPUT_DISABLED_BORDER}: var(${COLORS.GRAY_7});
      ${COLORS_INPUT.INPUT_ICON_COLOR}: var(${COLORS.GRAY_3});

      ${COLORS_RADIO.COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_RADIO.HOVER_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_RADIO.DISABLED_COLOR}: #454545;
      ${COLORS_RADIO.CHECKED_COLOR}: var(${COLORS.VIOLET_3});
      ${COLORS_RADIO.CHECKED_HOVER_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_RADIO.CHECKED_DISABLED_COLOR}: #454545;

      ${COLORS_SELECT.TEXT_COLOR}: var(${COLORS.WHITE});
      ${COLORS_SELECT.PLACEHOLDER_TEXT_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_SELECT.BACKGROUND}: var(${COLORS.GRAY_8});
      ${COLORS_SELECT.BACKGROUND_HOVER}: var(${COLORS.GRAY_7});
      ${COLORS_SELECT.BORDER_COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_SELECT.BORDER_HOVER_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_SELECT.BORDER_FOCUS_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_SELECT.DISABLED_BORDER_COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_SELECT.DISABLED_TEXT_COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_SELECT.DISABLED_BACKGROUND}: var(${COLORS.BLACK_1});
      ${COLORS_SELECT.DROPDOWN_BACKGROUND}: var(${COLORS.GRAY_8});
      ${COLORS_SELECT.DROPDOWN_HOVER_BACKGROUND}: var(${COLORS.GRAY_7});
      ${COLORS_SELECT.DROPDOWN_FOCUS_BACKGROUND}: var(${COLORS.GRAY_6});
      ${COLORS_SELECT.DROPDOWN_ICON_COLOR}: var(${COLORS.GRAY_4});
      ${COLORS_SELECT.DROPDOWN_ICON_HOVER_COLOR}: var(${COLORS.WHITE});
    }
  }
`;
