import { css } from '@linaria/core';

import {
  COLORS,
  COLORS_GENERAL,
  COLORS_BUTTON,
  COLORS_ICON,
  COLORS_DIVIDER,
  COLORS_SPIN,
  COLORS_MODAL,
  COLORS_TOOLTIP,
  COLORS_TAG,
  COLORS_INPUT,
  COLORS_RADIO,
  COLORS_SELECT,
  COLORS_BADGE,
  COLORS_TOOLBAR,
  COLORS_CHECKBOX,
  COLORS_CARD,
  COLORS_PAGINATE,
  COLORS_COLLAPSE_PANEL,
  COLORS_TABS,
  COLORS_STATUS,
  COLORS_SWITCH,
  COLORS_BREADCRUMBS,
} from './vars';

export const purple = css`
  :global() {
    [data-theme='purple'] {
      ${COLORS.GRAY_1}: #f5f5f5;
      ${COLORS.GRAY_2}: #ededed;
      ${COLORS.GRAY_3}: #d2d2d2;
      ${COLORS.GRAY_4}: #cfcfcf;
      ${COLORS.GRAY_5}: #cccccc;
      ${COLORS.GRAY_6}: #a0a0a0;
      ${COLORS.GRAY_7}: #6c6c6c;
      ${COLORS.BLACK_1}: #1b1b1b;
      ${COLORS.BLACK_2}: #343f48;
      ${COLORS.WHITE}: #ffffff;
      ${COLORS.VIOLET_1}: #f3f3fe;
      ${COLORS.VIOLET_2}: #e5e6fe;
      ${COLORS.VIOLET_3}: #bcbced;
      ${COLORS.VIOLET_4}: #aaabfc;
      ${COLORS.VIOLET_5}: #5558fa;
      ${COLORS.VIOLET_6}: #484bd5;
      ${COLORS.VIOLET_7}: #4042bc;
      ${COLORS.PURPLE}: #5c00ec;
      ${COLORS.GREEN_1}: #00ea95;
      ${COLORS.GREEN_2}: #07e897;
      ${COLORS.GREEN_3}: #12bba6;
      ${COLORS.BLUE_1}: #258CB8;
      ${COLORS.BLUE_2}: #375EC9;
      ${COLORS.RED_1}: #e84e58;
      ${COLORS.RED_2}: #ff0000;
      ${COLORS.YELLOW}: #f0d559;

      ${COLORS_GENERAL.BACKGROUND}: var(${COLORS.GRAY_2});
      ${COLORS_GENERAL.TEXT}: var(${COLORS.BLACK_2});

      ${COLORS_BUTTON.FOCUS_SHADOW}: var(${COLORS.VIOLET_2});

      ${COLORS_BUTTON.FILLED_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.FILLED_ICON_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.FILLED_BG}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.FILLED_HOVER_BG}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.FILLED_ACTIVE_BG}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.FILLED_DISABLED_COLOR}: var(${COLORS.VIOLET_2});
      ${COLORS_BUTTON.FILLED_DISABLED_BG}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.FILLED_FOCUS_BG}: var(${COLORS.VIOLET_6});

      ${COLORS_BUTTON.OUTLINED_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.OUTLINED_BORDER}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.OUTLINED_HOVER_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.OUTLINED_HOVER_BORDER}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.OUTLINED_ACTIVE_COLOR}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.OUTLINED_ACTIVE_BORDER}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.OUTLINED_DISABLED_COLOR}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.OUTLINED_DISABLED_BORDER}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.OUTLINED_FOCUS_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.OUTLINED_FOCUS_BORDER}: var(${COLORS.VIOLET_6});

      ${COLORS_BUTTON.TRANSPARENT_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.TRANSPARENT_HOVER_BG}: var(${COLORS.VIOLET_1});
      ${COLORS_BUTTON.TRANSPARENT_HOVER_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.TRANSPARENT_ACTIVE_BG}: var(${COLORS.VIOLET_2});
      ${COLORS_BUTTON.TRANSPARENT_ACTIVE_COLOR}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.TRANSPARENT_DISABLED_COLOR}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_BG}: var(${COLORS.VIOLET_1});
      ${COLORS_BUTTON.TRANSPARENT_FOCUS_BORDER}: var(${COLORS.VIOLET_6});

      ${COLORS_BUTTON.FILLED_BRAND_COLOR}: #343f48;
      ${COLORS_BUTTON.FILLED_BRAND_BG}: #07e897;
      ${COLORS_BUTTON.FILLED_BRAND_HOVER_BG}: #07d88d;
      ${COLORS_BUTTON.FILLED_BRAND_ACTIVE_BG}: #07cc85;
      ${COLORS_BUTTON.FILLED_BRAND_DISABLED_COLOR}: #cfcfcf;
      ${COLORS_BUTTON.FILLED_BRAND_DISABLED_BG}: var(${COLORS.GRAY_2});
      ${COLORS_BUTTON.FILLED_BRAND_FOCUS_BG}: #07d88d;

      ${COLORS_BUTTON.TABLE_MENU_BUTTON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_BUTTON.TABLE_MENU_BUTTON_HOVER_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.TABLE_MENU_BUTTON_DISABLED_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_BUTTON.TABLE_MENU_BUTTON_ACTIVE_COLOR}: var(${COLORS.VIOLET_6});

      ${COLORS_BUTTON.WHITE_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_BUTTON.WHITE_BG}: var(${COLORS.WHITE});
      ${COLORS_BUTTON.WHITE_HOVER_BG}: var(${COLORS.VIOLET_2});
      ${COLORS_BUTTON.WHITE_HOVER_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.WHITE_ACTIVE_BG}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.WHITE_ACTIVE_COLOR}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.WHITE_DISABLED_COLOR}: var(${COLORS.VIOLET_7});
      ${COLORS_BUTTON.WHITE_DISABLED_BG}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.WHITE_FOCUS_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_BUTTON.WHITE_FOCUS_BG}: var(${COLORS.VIOLET_2});
      ${COLORS_BUTTON.WHITE_FOCUS_OUTLINE}: var(${COLORS.VIOLET_4});
      ${COLORS_BUTTON.WHITE_FOCUS_BORDER}: transparent;

      ${COLORS_ICON.FILL}: var(${COLORS.GRAY_3});
      ${COLORS_ICON.HOVER_FILL}: var(${COLORS.VIOLET_5});
      ${COLORS_ICON.ACTIVE_FILL}: var(${COLORS.GRAY_2});

      ${COLORS_DIVIDER.COLOR_LIGHT}: var(${COLORS.GRAY_2});
      ${COLORS_DIVIDER.COLOR_MIDDLE}: #d2d2d2;
      ${COLORS_DIVIDER.COLOR_DARK}: var(${COLORS.BLACK_2});

      ${COLORS_SPIN.BORDER}: var(${COLORS.GRAY_3});
      ${COLORS_SPIN.BORDER_TOP}: var(${COLORS.GRAY_1});
      ${COLORS_SPIN.TEXT_COLOR}: var(${COLORS.BLACK_2});
      ${COLORS_SPIN.BORDER_REV}: var(${COLORS.WHITE});
      ${COLORS_SPIN.BORDER_REV_TOP}: #ffffff33;
      ${COLORS_SPIN.TEXT_REV_COLOR}: var(${COLORS.WHITE});

      ${COLORS_MODAL.BG}: var(${COLORS.WHITE});
      ${COLORS_MODAL.TITLE_COLOR}: var(${COLORS.BLACK_1});
      ${COLORS_MODAL.DESCRIPTION_COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_MODAL.PREVIEW_BG}: var(${COLORS.GRAY_2});
      ${COLORS_MODAL.PREVIEW_CLOSE_ICON_COLOR}: var(${COLORS.GRAY_6});
      ${COLORS_MODAL.PREVIEW_CLOSE_ICON_HOVER_COLOR}: var(${COLORS.BLACK_2});

      ${COLORS_TOOLTIP.CONTAINER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_TOOLTIP.CONTAINER_BG}: var(${COLORS.BLACK_2});
      ${COLORS_TOOLTIP.MENU_BG}: var(${COLORS.WHITE});
      ${COLORS_TOOLTIP.MENU_ITEM_HOVER_BG}: var(${COLORS.GRAY_2});
      ${COLORS_TOOLTIP.ICON_FILL}: var(${COLORS.GRAY_3});
      ${COLORS_TOOLTIP.ICON_HOVER_FILL}: var(${COLORS.WHITE});

      ${COLORS_TAG.TAG_TEXT_COLOR}: var(${COLORS.BLACK_1});
      ${COLORS_TAG.TAG_BG_GREEN}: #d7e7e2;
      ${COLORS_TAG.TAG_BG_BLUE}: #d5e4f7;
      ${COLORS_TAG.TAG_BG_PURPLE}: #dfd7f7;
      ${COLORS_TAG.TAG_BG_PINK}: #f5d5e5;
      ${COLORS_TAG.TAG_BG_RED}: #fbd6d5;
      ${COLORS_TAG.TAG_BG_GRAY_DEFAULT}: #e6e6e5;
      ${COLORS_TAG.TAG_BG_GRAY}: #d7d7d6;
      ${COLORS_TAG.TAG_BG_BROWN}: #e6d6d0;
      ${COLORS_TAG.TAG_BG_ORANGE}: #fae1d5;
      ${COLORS_TAG.TAG_BG_YELLOW}: #f9eed8;

      ${COLORS_INPUT.INPUT_BG}: var(${COLORS.WHITE});
      ${COLORS_INPUT.INPUT_BORDER}: var(${COLORS.GRAY_3});
      ${COLORS_INPUT.INPUT_PLACEHOLDER_COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_INPUT.INPUT_TEXT_COLOR}: var(${COLORS.BLACK_1});
      ${COLORS_INPUT.INPUT_HOVER_BORDER}: var(${COLORS.VIOLET_6});
      ${COLORS_INPUT.INPUT_HOVER_PLACEHOLDER_COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_INPUT.INPUT_ERROR}: var(${COLORS.RED_1});
      ${COLORS_INPUT.INPUT_FOCUS_BORDER}: var(${COLORS.VIOLET_6});
      ${COLORS_INPUT.INPUT_FOCUS_BACKGROUND}: var(${COLORS.WHITE});
      ${COLORS_INPUT.INPUT_HOVER_BACKGROUND}: var(${COLORS.WHITE});
      ${COLORS_INPUT.INPUT_DISABLED_BACKGROUND}: var(${COLORS.WHITE});
      ${COLORS_INPUT.INPUT_DISABLED_COLOR}: var(${COLORS.GRAY_6});
      ${COLORS_INPUT.INPUT_DISABLED_BORDER}: var(${COLORS.GRAY_3});
      ${COLORS_INPUT.INPUT_ICON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_INPUT.INPUT_ICON_HOVER_COLOR}: var(${COLORS.VIOLET_6});

      ${COLORS_RADIO.COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_RADIO.HOVER_COLOR}: var(${COLORS.GRAY_6});
      ${COLORS_RADIO.DISABLED_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_RADIO.CHECKED_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_RADIO.CHECKED_HOVER_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_RADIO.CHECKED_DISABLED_COLOR}: var(${COLORS.VIOLET_4});

      ${COLORS_SELECT.TEXT_COLOR}: var(${COLORS.BLACK_1});
      ${COLORS_SELECT.GROUP_HEADING_TEXT_COLOR}: var(${COLORS.GRAY_6});
      ${COLORS_SELECT.PLACEHOLDER_TEXT_COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_SELECT.BACKGROUND}: var(${COLORS.WHITE});
      ${COLORS_SELECT.BACKGROUND_HOVER}: var(${COLORS.WHITE});
      ${COLORS_SELECT.BACKGROUND_WITH_LOGO}: var(${COLORS.GRAY_1});
      ${COLORS_SELECT.BACKGROUND_WITH_LOGO_HOVER}: var(${COLORS.GRAY_2});
      ${COLORS_SELECT.BORDER_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_SELECT.BORDER_HOVER_COLOR}: var(${COLORS.VIOLET_4});
      ${COLORS_SELECT.BORDER_FOCUS_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_SELECT.DISABLED_BORDER_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_SELECT.DISABLED_TEXT_COLOR}: var(${COLORS.GRAY_6});
      ${COLORS_SELECT.DISABLED_BACKGROUND}: var(${COLORS.WHITE});
      ${COLORS_SELECT.DROPDOWN_BACKGROUND}: var(${COLORS.WHITE});
      ${COLORS_SELECT.DROPDOWN_HOVER_BACKGROUND}: var(${COLORS.GRAY_2});
      ${COLORS_SELECT.DROPDOWN_FOCUS_BACKGROUND}: var(${COLORS.GRAY_1});
      ${COLORS_SELECT.DROPDOWN_ICON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_SELECT.DROPDOWN_ICON_HOVER_COLOR}: var(${COLORS.BLACK_2});

      ${COLORS_BADGE.BORDER_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BADGE.TEXT_COLOR}: var(${COLORS.WHITE});
      ${COLORS_BADGE.DEFAULT_BACKGROUND}: var(${COLORS.VIOLET_5});

      ${COLORS_TOOLBAR.BACKGROUND}: var(${COLORS.WHITE});
      ${COLORS_TOOLBAR.INPUT_BORDER}: var(${COLORS.GRAY_2});
      ${COLORS_TOOLBAR.ACTIVE_BUTTON}: var(${COLORS.VIOLET_5});

      ${COLORS_CHECKBOX.CHECKBOX_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_CHECKBOX.CHECKBOX_HOVER_COLOR}: var(${COLORS.GRAY_6});
      ${COLORS_CHECKBOX.CHECKBOX_DISABLED_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_CHECKBOX.CHECKBOX_FILLED_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_CHECKBOX.CHECKBOX_FILLED_HOVER_COLOR}: var(${COLORS.VIOLET_6});
      ${COLORS_CHECKBOX.CHECKBOX_FILLED_DISABLED_COLOR}: var(${COLORS.VIOLET_4});

      ${COLORS_CARD.CARD_BACKGROUND}: var(${COLORS.WHITE});
      ${COLORS_CARD.CARD_HOVER_BACKGROUND}: var(${COLORS.WHITE});
      ${COLORS_CARD.CARD_SELECTED_BACKGROUND}: var(${COLORS.GRAY_2});
      ${COLORS_CARD.CARD_HOVER_SHADOW}: rgba(0, 0, 0, 0.1);
      ${COLORS_CARD.CARD_FAVOURITE_ICON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_CARD.CARD_FAVOURITE_ICON_HOVER_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_CARD.CARD_FAVOURITE_ICON_FILLED_COLOR}: var(${COLORS.YELLOW});

      ${COLORS_PAGINATE.PAGINATE_ACTIVE_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_PAGINATE.PAGINATE_DISABLED_COLOR}: var(${COLORS.VIOLET_4});
      ${COLORS_PAGINATE.PAGINATE_WHITE_COLOR}: var(${COLORS.WHITE});

      ${COLORS_COLLAPSE_PANEL.COLLAPSE_PANEL_BACKGROUND}: var(${COLORS.WHITE});
      ${COLORS_COLLAPSE_PANEL.COLLAPSE_PANEL_BACKGROUND_HOVER}: var(${COLORS.WHITE});
      ${COLORS_COLLAPSE_PANEL.COLLAPSE_PANEL_FAVOURITE_ICON_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_COLLAPSE_PANEL.COLLAPSE_PANEL_FAVOURITE_ICON_HOVER_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_COLLAPSE_PANEL.COLLAPSE_PANEL_FAVOURITE_ICON_FILLED_COLOR}: var(${COLORS.YELLOW});

      ${COLORS_TABS.TAB_ACTIVE_COLOR}: var(${COLORS.VIOLET_5});
      ${COLORS_TABS.TAB_BORDER_COLOR}: var(${COLORS.GRAY_2});
      ${COLORS_TABS.TAB_GRAY_BORDER_COLOR}: var(${COLORS.GRAY_3});
      ${COLORS_TABS.TAB_TEXT_COLOR}: var(${COLORS.GRAY_6});

      ${COLORS_STATUS.COLOR}: var(${COLORS.GRAY_7});
      ${COLORS_STATUS.FAILED_BG}: var(${COLORS.RED_2});
      ${COLORS_STATUS.SUCCESS_BG}: var(${COLORS.GREEN_2});
      ${COLORS_STATUS.WARNING_BG}: var(${COLORS.YELLOW});
      ${COLORS_STATUS.UNACTIVE_BG}: var(${COLORS.GRAY_6});

      ${COLORS_SWITCH.UNACTIVE_BG}: var(${COLORS.GRAY_3});
      ${COLORS_SWITCH.UNACTIVE_HOVER_BG}: var(${COLORS.GRAY_6});
      ${COLORS_SWITCH.UNACTIVE_DISABLED_BG}: var(${COLORS.GRAY_3});
      ${COLORS_SWITCH.ACTIVE_BG}: var(${COLORS.VIOLET_5});
      ${COLORS_SWITCH.ACTIVE_HOVER_BG}: var(${COLORS.VIOLET_6});
      ${COLORS_SWITCH.ACTIVE_DISABLED_BG}: var(${COLORS.VIOLET_4});

      ${COLORS_BREADCRUMBS.ACTIVE_COLOR}: var(${COLORS.BLACK_1});
      ${COLORS_BREADCRUMBS.INACTIVE_COLOR}: var(${COLORS.GRAY_7});
    }
  }
`;
