import {
  BareMetalSVG,
  ElasticCloudServerWithGpuSVG,
  EvolutionComputeSVG,
  ManagedKubernetesSVG,
  ManagedPostgreSqlSVG,
  S3StorageSVG,
} from '@sbercloud/uikit-product-icons';

import { PLATFORM } from '../../../constants';
import { CatalogConfig } from '../../../types';
import { EVOLUTION_PRODUCT } from './constants';
import {
  EVOLUTION_BARE_METAL_FORM_CONFIG,
  EVOLUTION_CLOUD_SERVER_FORM_CONFIG,
  EVOLUTION_CLOUD_SERVER_FREE_TIER_FORM_CONFIG,
  EVOLUTION_CLOUD_SERVER_GPU_FORM_CONFIG,
  EVOLUTION_KUBERNETES_FORM_CONFIG,
  EVOLUTION_POSTGRE_SQL_FORM_CONFIG,
  EVOLUTION_STORAGE_S3_FORM_CONFIG,
  EVOLUTION_STORAGE_S3_FREE_TIER_FORM_CONFIG,
} from './product-config';

export const EVOLUTION_PRODUCTS: CatalogConfig['products'] = {
  [EVOLUTION_PRODUCT.EvolutionCloudServer]: {
    id: EVOLUTION_PRODUCT.EvolutionCloudServer,
    platform: PLATFORM.Evolution,
    label: 'Evolution Compute',
    caption: 'Виртуальные машины для развертывания сервисов и приложений',
    icon: EvolutionComputeSVG,
    dataTestId: 'evolutionCloudServer',
    formConfig: EVOLUTION_CLOUD_SERVER_FORM_CONFIG,
    enableChangeProductQuantity: true,
    enableConnectToConsole: true,
  },
  [EVOLUTION_PRODUCT.EvolutionCloudServerFreeTier]: {
    id: EVOLUTION_PRODUCT.EvolutionCloudServerFreeTier,
    platform: PLATFORM.Evolution,
    label: 'Evolution Compute Free Tier',
    caption: 'Бесплатная виртуальная машина в заданной конфигурации',
    formConfig: EVOLUTION_CLOUD_SERVER_FREE_TIER_FORM_CONFIG,
    icon: EvolutionComputeSVG,
    dataTestId: 'evolutionCloudServerFreeTier',
    freeTier: true,
    enableConnectToConsole: true,
  },
  [EVOLUTION_PRODUCT.EvolutionKubernetes]: {
    id: EVOLUTION_PRODUCT.EvolutionKubernetes,
    platform: PLATFORM.Evolution,
    label: 'Evolution Managed Kubernetes',
    caption: 'Управление контейнерными приложениями в кластере Kubernetes',
    formConfig: EVOLUTION_KUBERNETES_FORM_CONFIG,
    icon: ManagedKubernetesSVG,
    dataTestId: 'evolutionKubernetes',
    enableChangeProductQuantity: true,
    enableConnectToConsole: true,
  },
  [EVOLUTION_PRODUCT.EvolutionStorageS3FreeTier]: {
    id: EVOLUTION_PRODUCT.EvolutionStorageS3FreeTier,
    platform: PLATFORM.Evolution,
    label: 'Evolution Object Storage Free Tier',
    caption: 'Ежемесячный объем бесплатных ресурсов в хранилище',
    formConfig: EVOLUTION_STORAGE_S3_FREE_TIER_FORM_CONFIG,
    icon: S3StorageSVG,
    dataTestId: 'evolutionStorageS3FreeTier',
    freeTier: true,
    enableConnectToConsole: true,
  },
  [EVOLUTION_PRODUCT.EvolutionStorageS3]: {
    id: EVOLUTION_PRODUCT.EvolutionStorageS3,
    platform: PLATFORM.Evolution,
    label: 'Evolution Object Storage',
    caption: 'Масштабируемое хранилище S3 для всех типов данных',
    icon: S3StorageSVG,
    formConfig: EVOLUTION_STORAGE_S3_FORM_CONFIG,
    dataTestId: 'evolutionStorageS3',
    enableChangeProductQuantity: true,
    enableConnectToConsole: true,
  },
  [EVOLUTION_PRODUCT.EvolutionManagedPostgreSQL]: {
    id: EVOLUTION_PRODUCT.EvolutionManagedPostgreSQL,
    platform: PLATFORM.Evolution,
    label: 'Evolution Managed PostgreSQL®',
    caption: 'Управляемые базы данных PostgreSQL®',
    icon: ManagedPostgreSqlSVG,
    formConfig: EVOLUTION_POSTGRE_SQL_FORM_CONFIG,
    dataTestId: 'evolutionPostgreSql',
    enableChangeProductQuantity: true,
    enableConnectToConsole: true,
  },
  [EVOLUTION_PRODUCT.EvolutionBareMetal]: {
    id: EVOLUTION_PRODUCT.EvolutionBareMetal,
    platform: PLATFORM.Evolution,
    label: 'Evolution Bare Metal',
    caption: 'Сервис аренды физических серверов с доступом и управлением только для вас',
    icon: BareMetalSVG,
    formConfig: EVOLUTION_BARE_METAL_FORM_CONFIG,
    dataTestId: EVOLUTION_PRODUCT.EvolutionBareMetal,
    enableChangeProductQuantity: false,
    enableConnectToConsole: true,
  },
  [EVOLUTION_PRODUCT.EvolutionCloudServerGpu]: {
    id: EVOLUTION_PRODUCT.EvolutionCloudServerGpu,
    platform: PLATFORM.Evolution,
    label: 'Вычислительные мощности с GPU',
    caption: 'Аренда виртуальных машин, серверов и ML-сервисов с графическими ускорителями',
    icon: ElasticCloudServerWithGpuSVG,
    formConfig: EVOLUTION_CLOUD_SERVER_GPU_FORM_CONFIG,
    dataTestId: EVOLUTION_PRODUCT.EvolutionCloudServerGpu,
    enableChangeProductQuantity: true,
    enableConnectToConsole: false,
  },
};
