import { PlaceholderSVG } from '@cloud-ru/uikit-product-icons';

import { LinksGroup } from '../src';

const EMPTY_ON_CLICK = () => {};
const EMPTY_HREF = '#';

export const SERVICE_GROUPS: LinksGroup[] = [
  {
    label: { text: 'Инфраструктура' },
    id: 'svpInfrastructure',
    items: [
      {
        id: 'vms',
        label: 'Виртуальные машины',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['виртуальные машины', 'vm', 'virtual machine', 'виртмашины'],
      },
      {
        id: 'anti-affinity',
        label: 'Группы размещения',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['группы размещения', 'placement groups'],
      },
      {
        id: 'images',
        label: 'Образы',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['образы', 'шаблоны', 'images', 'ISO'],
      },
      {
        id: 'sshKeys',
        label: 'SSH-ключи',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['ssh ключ', 'ssh keys', 'ключи доступа'],
      },
      {
        id: 'backups',
        label: 'Резервное копирование',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['backup', 'бэкап', 'резервное копирование', 'восстановление', 'копия'],
      },
      {
        id: 'bareMetal',
        label: 'Bare Metal',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['выделенные серверы', 'бэреметал', 'бареметал', 'железные серверы'],
      },
    ],
  },
  {
    label: { text: 'Сеть' },
    id: 'svpNetwork',
    items: [
      {
        id: 'subnets',
        label: 'Подсети',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['подсеть', 'субнет', 'subnets', 'сеть'],
      },
      {
        id: 'vpc',
        label: 'VPC',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['vpc', 'виртуальная сеть', 'virtual private cloud', 'виртуальный облачный контур'],
      },
      {
        id: 'publicIp',
        label: 'Публичные IP',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['ip', 'публичный', 'внешний', 'floating'],
      },
      {
        id: 'gateways',
        label: 'sNAT-шлюзы',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        badge: 'Preview',
        aliases: ['snat', 'шлюзы', 'gateways', 'гейтвей'],
      },
      {
        id: 'securityGroups',
        label: 'Группы безопасности',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['группа безопасности', 'security group', 'firewall group'],
      },
      {
        id: 'loadBalancer',
        label: 'Балансировщик нагрузки',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        badge: { text: 'New', appearance: 'pink' },
        aliases: ['балансировщик', 'load balancer', 'балансировка'],
      },
      {
        id: 'cloudDns',
        label: 'Cloud DNS',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['cloud dns', 'облачный днс', 'dns в облаке'],
      },
      {
        id: 'dns',
        label: 'DNS',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['dns', 'доменные имена', 'днс'],
      },
      {
        id: 'magicRouter',
        label: 'Magic Router',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['magic router', 'магический маршрутизатор', 'маршрутизатор'],
      },
      {
        id: 'virtualIp',
        label: 'Virtual IP',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['virtual ip', 'виртуальные IP адреса', 'vip'],
      },
    ],
  },
  {
    label: {
      text: 'Хранение данных',
      onClick: () => undefined,
    },
    id: 'svpDataStorage',
    items: [
      {
        id: 'disks',
        label: 'Диски',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['диск', 'disks', 'volume', 'хранилище', 'storage', 'volumes'],
      },
      {
        id: 's3',
        label: 'S3 Objective Storage',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['object storage', 'объектное хранилище', 'облачное хранилище', 'bucket', 'бакет'],
      },
    ],
  },
  {
    label: { text: 'Контейнеры' },
    id: 'svpContainers',
    items: [
      {
        id: 'managedKubernetes',
        label: 'Managed Kubernetes',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['managed k8s', 'управляемый кубернетес', 'kubernetes managed'],
      },
      {
        id: 'artifactRegistry',
        label: 'Artifact Registry',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['артефакт', 'artifact registry', 'реестр', 'регистр', 'докер', 'docker-образ', 'debian'],
      },
      {
        id: 'containerApps',
        label: 'Container Apps',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['контейнерные приложения', 'container apps', 'app контейнер', 'приложения контейнеры'],
      },
    ],
  },
  {
    label: { text: 'Разработка' },
    id: 'svpDevelopment',
    items: [
      {
        id: 'apiGateway',
        label: 'API gateway',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['апи', 'api', 'шлюзы', 'гейтвей', 'маршрутизатор'],
      },
      {
        id: 'serverlessFunctions',
        label: 'Serverless functions',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['функции без сервера', 'lambda', 'лямбда', 'serverless functions'],
      },
    ],
  },
  {
    label: { text: 'Брокеры сообщений' },
    id: 'svpBrokers',
    items: [
      {
        id: 'kafka',
        label: 'Managed Kafka®',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['managed kafka', 'кафка'],
      },
      {
        id: 'corax',
        label: 'Managed Corax',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['managed corax', 'брокер коракс'],
      },
    ],
  },
  {
    label: { text: 'Базы данных' },
    id: 'svpDatabases',
    items: [
      {
        id: 'postgreSQL',
        label: 'Managed PostgreSQL®',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['postgresql', 'pgsql', 'постгрес'],
      },
      {
        id: 'timescaleDB',
        label: 'Managed TimescaleDB®',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['документоориентированная бд', 'document db'],
      },
      {
        id: 'pangolin',
        label: 'Managed Pangolin',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['панголин'],
      },
      {
        id: 'dataGrid',
        label: 'Managed DataGrid',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['датагрид'],
      },
      {
        id: 'redis',
        label: 'Managed Redis®',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['in-memory бд', 'редис'],
      },
      {
        id: 'clickhouse',
        label: 'Managed Clickhouse',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['кликхаус'],
      },
      {
        id: 'openSearch',
        label: 'Managed OpenSearch',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['open search'],
      },
      {
        id: 'search',
        label: 'Managed Search',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['документоориентированная бд', 'document db'],
      },
    ],
  },
  {
    label: { text: 'Инструменты разработчика' },
    id: 'svpDevtools',
    items: [
      {
        id: 'repo',
        label: 'Repo',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['репозиторий', 'git', 'хранение кода', 'codebase'],
      },
      {
        id: 'pipeline',
        label: 'Pipeline',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['пайплайн', 'pipeline', 'ci cd', 'workflow', 'автоматизация'],
      },
    ],
  },
  {
    label: { text: 'Платформа данных' },
    id: 'svpDataPlatform',
    items: [
      {
        id: 'trino',
        label: 'Managed Trino',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['sql engine', 'trino-db', 'трино'],
      },
      {
        id: 'metastore',
        label: 'Managed Metastore',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['хранилище метаданных', 'метастор'],
      },
      {
        id: 'arenadata',
        label: 'Managed ArenadataDB',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['greenplum', 'аналитика', 'аренадата'],
      },
      {
        id: 'spark',
        label: 'Managed Spark',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['спарк'],
      },
      {
        id: 'bi',
        label: 'Managed BI',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['аналитика', 'analytics', 'superset'],
      },
      {
        id: 'airflow',
        label: 'Managed Airflow',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['оркестрация', 'задачи данных', 'эирфлоу'],
      },
    ],
  },
  {
    label: { text: 'ML/AI инструменты' },
    id: 'svpInference',
    items: [
      {
        id: 'inference',
        label: 'ML Inference',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['ml inference', 'инференс', 'ai', 'hugging face', 'ollama'],
      },
      {
        id: 'notebooks',
        label: 'Notebooks',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['блокноты', 'jupyter', 'ноутбуки'],
      },
      {
        id: 'foundationModels',
        label: 'Foundation Models',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['модель', 'llm'],
      },
      {
        id: 'mlFinetuning',
        label: 'ML Finetuning',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['lora', 'low-rank adaptation', 'лора', 'finetuning', 'дообучение'],
      },
    ],
  },
  {
    label: { text: 'Управление' },
    id: 'svpManagement',
    items: [
      {
        id: 'tasksHistory',
        label: 'История задач',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['история задач', 'tasks history', 'log'],
      },
      {
        id: 'tags',
        label: 'Теги',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['теги', 'labels', 'метки', 'tags'],
      },
      {
        id: 'sckm',
        label: 'Key Management',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['key management', 'kms', 'управление ключами'],
      },
      {
        id: 'secretManager',
        label: 'Secret Management',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['secret management', 'управляемые секреты', 'секрет менеджер'],
      },
    ],
  },
  {
    label: { text: 'Гибридные сервисы' },
    id: 'svpHybrid',
    items: [
      {
        id: 'vmManager',
        label: 'Управление ПО',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['управление программным обеспечением', 'менеджер ПО'],
      },
      {
        id: 'vcenterManager',
        label: 'Платформы виртуализации',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: [
          'vcenter manager',
          'платформы виртуализации',
          'менеджер виртуализации',
          'VMware',
          'virtualization platform',
        ],
      },
      {
        id: 'vcenterVM',
        label: 'ВМ платформ виртуализации',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['виртуальная машина', 'vm vcenter', 'вм платформы', 'виртуализация vm'],
      },
      {
        id: 'basisVM',
        label: 'ВМ Базис IaaS',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['вм базис', 'iaas vm', 'базис иаас', 'basis iaas'],
      },
      {
        id: 'edgeManager',
        label: 'Edge',
        onClick: EMPTY_ON_CLICK,
        href: EMPTY_HREF,
        icon: PlaceholderSVG,
        aliases: ['эдж'],
      },
    ],
  },
];

export const SETTING_ITEMS = [
  'Мониторинг',
  'Контроль затрат',
  'Администрирование',
  'Пользователи',
  'Поддержка',
  'Документация',
].map(label => ({
  content: {
    option: label,
  },
  beforeContent: <PlaceholderSVG />,
}));
