import { createTextProvider, LanguageCodeType } from '@sbercloud/uikit-product-utils';

export enum Texts {
  HeaderBalanceTooltipBalance = 'header-balance-tooltip-balance',
  HeaderBalanceTooltipLimit = 'header-balance-tooltip-limit',
  HeaderBalanceTooltipBonuses = 'header-balance-tooltip-bonuses',
  HeaderBalanceTooltipRecharge = 'header-balance-tooltip-recharge',

  HeaderProjectSelectorCreateProject = 'header-project-selector-create-project',
  HeaderProjectSelectorCreateWorkspace = 'header-project-selector-create-workspace',
  HeaderProjectSelectorEditOption = 'header-project-selector-edit-option',

  NoDataFound = 'no-data-found',

  // ЛК 2.0
  Menu = 'menu',
  SearchByServices = 'search-by-services',
  NoData = 'no-data',
  Notifications = 'notifications',
  NotificationsAll = 'notifications-all',
  NotificationsUnread = 'notifications-unread',
  NotificationsErrorTitle = 'notifications-error-title',
  NotificationsErrorDescription = 'notifications-error-description',
  MarkAllAsRead = 'mark-all-as-read',
  NotificationsFooterButton = 'notifications-footer-button',
  NoNotificationsTitle = 'no-notifications-title',
  NoNotificationsDescription = 'no-notifications-description',
  NotificationsDivider = 'notifications-divider',
  Search = 'search',
  Edit = 'edit',
  Organization = 'organization',
  AddOrganization = 'add-organization',
  OrganizationNewBadge = 'organization-new-badge',
  InvitePopoverTitle = 'invite-popover-title',
  InvitePopoverText = 'invite-popover-text',
  InvitePopoverAcceptButton = 'invite-popover-accept-button',
  InvitePopoverCancelButton = 'invite-popover-cancel-button',
  Project = 'project',
  AddProject = 'add-project',
  Platforms = 'platforms',
  ManageProfile = 'manage-profile',
  SwitchTheme = 'switch-theme',
  Logout = 'logout',
  Workspaces = 'workspaces',
  AddWorkspace = 'add-workspace',
}

const dictionary: Partial<Record<LanguageCodeType, Record<Texts, string>>> = {
  [LanguageCodeType.ruRU]: {
    [Texts.HeaderBalanceTooltipBalance]: 'Баланс',
    [Texts.HeaderBalanceTooltipLimit]: 'Лимит',
    [Texts.HeaderBalanceTooltipBonuses]: 'Бонусы',
    [Texts.HeaderBalanceTooltipRecharge]: 'Пополнить баланс',

    [Texts.HeaderProjectSelectorCreateProject]: 'Создать проект',
    [Texts.HeaderProjectSelectorCreateWorkspace]: 'Создать workspace',
    [Texts.HeaderProjectSelectorEditOption]: 'Редактировать',

    [Texts.NoDataFound]: 'Ничего не найдено',

    // ЛК 2.0
    [Texts.Menu]: 'Меню',
    [Texts.SearchByServices]: 'Поиск по сервисам',
    [Texts.NoData]: 'Нет данных',
    [Texts.Notifications]: 'Уведомления',
    [Texts.NotificationsAll]: 'Все',
    [Texts.NotificationsUnread]: 'Новые',
    [Texts.MarkAllAsRead]: 'Отметить все как прочитанное',
    [Texts.NoNotificationsTitle]: 'Нет уведомлений',
    [Texts.NoNotificationsDescription]: 'Здесь вы увидите новые уведомления о событиях, когда что-то произойдет',
    [Texts.NotificationsErrorTitle]: 'Уже чиним',
    [Texts.NotificationsErrorDescription]: 'Скоро здесь появятся ваши уведомления',
    [Texts.NotificationsDivider]: 'Прочитанные',
    [Texts.NotificationsFooterButton]: 'Все события',

    [Texts.Search]: 'Поиск',
    [Texts.Edit]: 'Редактировать',
    [Texts.Organization]: 'Организации',
    [Texts.AddOrganization]: 'Добавить организацию',
    [Texts.OrganizationNewBadge]: 'Новая',
    [Texts.InvitePopoverTitle]: 'Теперь вам доступна другая организация',
    [Texts.InvitePopoverText]: 'Сменить организацию можно нажав на профиль',
    [Texts.InvitePopoverAcceptButton]: 'Сменить сейчас',
    [Texts.InvitePopoverCancelButton]: 'Закрыть',
    [Texts.Project]: 'Проекты',
    [Texts.AddProject]: 'Добавить проект',
    [Texts.Platforms]: 'Платформы',
    [Texts.ManageProfile]: 'Управление профилем',
    [Texts.SwitchTheme]: 'Переключить тему',
    [Texts.Logout]: 'Выйти из аккаунта',
    [Texts.Workspaces]: 'Воркспейсы',
    [Texts.AddWorkspace]: 'Добавить воркспейс',
  },
  [LanguageCodeType.enGB]: {
    [Texts.HeaderBalanceTooltipBalance]: 'Balance',
    [Texts.HeaderBalanceTooltipLimit]: 'Limit',
    [Texts.HeaderBalanceTooltipBonuses]: 'Bonuses',
    [Texts.HeaderBalanceTooltipRecharge]: 'Recharge the balance',

    [Texts.HeaderProjectSelectorCreateProject]: 'Create project',
    [Texts.HeaderProjectSelectorCreateWorkspace]: 'Create workspace',
    [Texts.HeaderProjectSelectorEditOption]: 'Edit',

    [Texts.NoDataFound]: 'Nothing found',

    // ЛК 2.0
    [Texts.Menu]: 'Menu',
    [Texts.SearchByServices]: 'Search by service',
    [Texts.NoData]: 'Nothing found',
    [Texts.Notifications]: 'Notifications',
    [Texts.NotificationsAll]: 'All',
    [Texts.NotificationsUnread]: 'Unread',
    [Texts.MarkAllAsRead]: 'Mark all as read',
    [Texts.NoNotificationsTitle]: 'No notifications',
    [Texts.NoNotificationsDescription]: "This is where you'll see new event notifications when something happens",
    [Texts.NotificationsErrorTitle]: "We're already fixing it",
    [Texts.NotificationsErrorDescription]: 'Your notifications will appear here soon',
    [Texts.NotificationsDivider]: 'Already read',
    [Texts.NotificationsFooterButton]: 'All events',

    [Texts.Search]: 'Search',
    [Texts.Edit]: 'Edit',
    [Texts.Organization]: 'Organizations',
    [Texts.AddOrganization]: 'Add organization',
    [Texts.OrganizationNewBadge]: 'New',
    [Texts.InvitePopoverTitle]: 'A different organization is now available to you',
    [Texts.InvitePopoverText]: 'You can change your organization by clicking on your profile',
    [Texts.InvitePopoverAcceptButton]: 'Change now',
    [Texts.InvitePopoverCancelButton]: 'Cancel',
    [Texts.Project]: 'Projects',
    [Texts.AddProject]: 'Add projects',
    [Texts.Platforms]: 'Platforms',
    [Texts.ManageProfile]: 'Manage profile',
    [Texts.SwitchTheme]: 'Switch theme',
    [Texts.Logout]: 'Logout',
    [Texts.Workspaces]: 'Workspaces',
    [Texts.AddWorkspace]: 'Add workspace',
  },
};

export const textProvider = createTextProvider<Texts>(dictionary, 'navigation');
