import { createTextProvider, LanguageCodeType } from '@sbercloud/uikit-product-utils';

export enum Texts {
  HeaderProjectSelectorCreateProject = 'header-project-selector-create-project',
  HeaderProjectSelectorCreateWorkspace = 'header-project-selector-create-workspace',
  HeaderProjectSelectorEditOption = 'header-project-selector-edit-option',

  NoDataFound = 'no-data-found',

  // ЛК 2.0
  Menu = 'menu',
  Navigation = 'Navigation',
  SearchByServices = 'search-by-services',
  NoData = 'no-data',
  Notifications = 'notifications',
  NotificationsAll = 'notifications-all',
  NotificationsUnread = 'notifications-unread',
  NotificationsErrorTitle = 'notifications-error-title',
  NotificationsErrorDescription = 'notifications-error-description',
  MarkAllAsRead = 'mark-all-as-read',
  NotificationsFooterButton = 'notifications-footer-button',
  NoNotificationsTitle = 'no-notifications-title',
  NoNotificationsDescription = 'no-notifications-description',
  NotificationsDivider = 'notifications-divider',
  Search = 'search',
  SearchCloseButton = 'search-close-button',
  SearchOpenButton = 'search-open-button',
  SearchProjectsPlaceholder = 'search-projects-placeholder',
  SearchWorkspacesPlaceholder = 'search-workspaces-placeholder',
  Edit = 'edit',
  Organizations = 'organizations',
  AddOrganization = 'add-organization',
  OrganizationNewBadge = 'organization-new-badge',
  PartnerOrganizationBadge = 'partner-organization-badge',
  InvitePopoverTitle = 'invite-popover-title',
  InvitePopoverText = 'invite-popover-text',
  InvitePopoverAcceptButton = 'invite-popover-accept-button',
  InvitePopoverCancelButton = 'invite-popover-cancel-button',
  Projects = 'projects',
  AddProject = 'add-project',
  Platforms = 'platforms',
  ManageProfile = 'manage-profile',
  SwitchTheme = 'switch-theme',
  Logout = 'logout',
  Workspaces = 'workspaces',
  AddWorkspace = 'add-workspace',
  Favorite = 'favorite',

  FinancialMenuTitle = 'financial-menu-title',
  FinancialMenuEyeButtonDataVisibleTip = 'financial-menu-eye-button-data-visible-tip',
  FinancialMenuEyeButtonDataHiddenTip = 'financial-menu-eye-button-data-hidden-tip',
  FinancialMenuBonusSign = 'financial-menu-bonus-sign',
  FinancialMenuDrawerTitle = 'financial-menu-drawer-title',
  FinancialMenuTooltipMoreButton = 'financial-menu-tooltip-more-button',
  FinancialMenuBalanceAction = 'financial-menu-balance-action',
  FinancialMenuBonusesAction = 'financial-menu-bonuses-action',
  FinancialMenuGrantInfinity = 'financial-menu-grant-infinity',
  FinancialMenuNoGrants = 'financial-menu-no-grants',
  FinancialMenuGrantStatusSpending = 'financial-menu-grant-status-spending',
  FinancialMenuGrantStatusNotSpending = 'financial-menu-grant-status-not-spending',
  FinancialMenuGrantStatusNotStart = 'financial-menu-grant-status-not-start',
  FinancialMenuAddServicesLink = 'financial-menu-add-services-link',
  FinancialMenuGetGrant = 'financial-menu-get-starter-grant',
  FinancialMenuGrantIsOnTheWay = 'financial-menu-grant-is-on-the-way',
  FinancialMenuStarterGrantName = 'financial-menu-starter-grant-name',

  Project = 'project',
  Workspace = 'workspace',
  Organization = 'organization',

  ThemeModeLight = 'theme-mode-light',
  ThemeModeDark = 'theme-mode-dark',
  ThemeModeSystem = 'theme-mode-system',
  ThemeModeLabel = 'theme-mode-label',

  PartnerPopoverTitle = 'partner-popover-title',
  PartnerPopoverText = 'partner-popover-text',
  PartnerPopoverDescription = 'partner-popover-description',
  PartnerPopoverCancelButton = 'partner-popover-cancel-button',
}

const dictionary: Partial<Record<LanguageCodeType, Record<Texts, string>>> = {
  [LanguageCodeType.ruRU]: {
    [Texts.HeaderProjectSelectorCreateProject]: 'Создать проект',
    [Texts.HeaderProjectSelectorCreateWorkspace]: 'Создать workspace',
    [Texts.HeaderProjectSelectorEditOption]: 'Редактировать',

    [Texts.NoDataFound]: 'Ничего не найдено',

    // ЛК 2.0
    [Texts.Menu]: 'Меню',
    [Texts.Navigation]: 'Навигация',
    [Texts.SearchByServices]: 'Поиск по сервисам',
    [Texts.NoData]: 'Нет данных',
    [Texts.Notifications]: 'Уведомления',
    [Texts.NotificationsAll]: 'Все',
    [Texts.NotificationsUnread]: 'Новые',
    [Texts.MarkAllAsRead]: 'Отметить все как прочитанное',
    [Texts.NoNotificationsTitle]: 'Нет уведомлений',
    [Texts.NoNotificationsDescription]: 'Здесь вы увидите новые уведомления о событиях, когда что-то произойдет',
    [Texts.NotificationsErrorTitle]: 'Уже чиним',
    [Texts.NotificationsErrorDescription]: 'Скоро здесь появятся ваши уведомления',
    [Texts.NotificationsDivider]: 'Прочитанные',
    [Texts.NotificationsFooterButton]: 'Все события',

    [Texts.Search]: 'Поиск',
    [Texts.SearchCloseButton]: 'Закрыть поиск',
    [Texts.SearchOpenButton]: 'Открыть поиск',
    [Texts.Edit]: 'Редактировать',
    [Texts.Organizations]: 'Организации',
    [Texts.AddOrganization]: 'Добавить организацию',
    [Texts.OrganizationNewBadge]: 'Новая',
    [Texts.PartnerOrganizationBadge]: 'Партнер',
    [Texts.InvitePopoverTitle]: 'Теперь вам доступна другая организация',
    [Texts.InvitePopoverText]: 'Сменить организацию можно нажав на профиль',
    [Texts.InvitePopoverAcceptButton]: 'Сменить сейчас',
    [Texts.InvitePopoverCancelButton]: 'Закрыть',
    [Texts.Projects]: 'Проекты',
    [Texts.AddProject]: 'Добавить проект',
    [Texts.Platforms]: 'Платформы',
    [Texts.ManageProfile]: 'Управление профилем',
    [Texts.SwitchTheme]: 'Переключить тему',
    [Texts.Logout]: 'Выйти из аккаунта',
    [Texts.Workspaces]: 'Воркспейсы',
    [Texts.AddWorkspace]: 'Добавить воркспейс',
    [Texts.Favorite]: 'Избранное',

    [Texts.FinancialMenuTitle]: 'Контроль затрат',
    [Texts.FinancialMenuEyeButtonDataVisibleTip]: 'Скрыть баланс в шапке',
    [Texts.FinancialMenuEyeButtonDataHiddenTip]: 'Показать баланс в шапке',
    [Texts.FinancialMenuBonusSign]: 'Б',
    [Texts.FinancialMenuDrawerTitle]: 'Баланс',
    [Texts.FinancialMenuTooltipMoreButton]: 'Подробнее',
    [Texts.FinancialMenuBalanceAction]: 'Пополнить баланс',
    [Texts.FinancialMenuBonusesAction]: 'Ввести промокод',
    [Texts.FinancialMenuGrantInfinity]: 'без срока',
    [Texts.FinancialMenuNoGrants]: 'Грантов пока нет',
    [Texts.FinancialMenuGrantStatusSpending]: 'Тратится',
    [Texts.FinancialMenuGrantStatusNotSpending]: 'Не тратится',
    [Texts.FinancialMenuGrantStatusNotStart]: 'Срок действия пока не наступил',
    [Texts.FinancialMenuAddServicesLink]: 'Подключить сервисы',
    [Texts.FinancialMenuGetGrant]: 'Получить грант',
    [Texts.FinancialMenuGrantIsOnTheWay]: 'Грант уже в пути',
    [Texts.FinancialMenuStarterGrantName]: 'Все сервисы, без GPU',

    [Texts.Project]: 'Проект',
    [Texts.Workspace]: 'Воркспейс',
    [Texts.Organization]: 'Организация',

    [Texts.SearchProjectsPlaceholder]: 'Поиск по проектам',
    [Texts.SearchWorkspacesPlaceholder]: 'Поиск по воркспейсам',

    [Texts.ThemeModeLight]: 'Светлая',
    [Texts.ThemeModeDark]: 'Темная',
    [Texts.ThemeModeSystem]: 'Системная',
    [Texts.ThemeModeLabel]: 'Тема интерфейса',

    [Texts.PartnerPopoverTitle]: 'Доступна новая организация',
    [Texts.PartnerPopoverText]: 'Для нее одобрена заявка на участие в реферальной программе.',
    [Texts.PartnerPopoverDescription]:
      'Переключитесь на эту организацию, чтобы начать работу в партнерском кабинете. Переключаться между организациями можно в профиле или в меню выбора проекта.',
    [Texts.PartnerPopoverCancelButton]: 'Больше не показывать',
  },
  [LanguageCodeType.enGB]: {
    [Texts.HeaderProjectSelectorCreateProject]: 'Create project',
    [Texts.HeaderProjectSelectorCreateWorkspace]: 'Create workspace',
    [Texts.HeaderProjectSelectorEditOption]: 'Edit',

    [Texts.NoDataFound]: 'Nothing found',

    // ЛК 2.0
    [Texts.Menu]: 'Menu',
    [Texts.Navigation]: 'Navigation',
    [Texts.SearchByServices]: 'Search by service',
    [Texts.NoData]: 'No data',
    [Texts.Notifications]: 'Notifications',
    [Texts.NotificationsAll]: 'All',
    [Texts.NotificationsUnread]: 'Unread',
    [Texts.MarkAllAsRead]: 'Mark all as read',
    [Texts.NoNotificationsTitle]: 'No notifications',
    [Texts.NoNotificationsDescription]: "This is where you'll see new event notifications when something happens",
    [Texts.NotificationsErrorTitle]: "We're already fixing it",
    [Texts.NotificationsErrorDescription]: 'Your notifications will appear here soon',
    [Texts.NotificationsDivider]: 'Already read',
    [Texts.NotificationsFooterButton]: 'All events',

    [Texts.Search]: 'Search',
    [Texts.SearchCloseButton]: 'Close search',
    [Texts.SearchOpenButton]: 'Open search',
    [Texts.Edit]: 'Edit',
    [Texts.Organizations]: 'Organizations',
    [Texts.AddOrganization]: 'Add organization',
    [Texts.OrganizationNewBadge]: 'New',
    [Texts.PartnerOrganizationBadge]: 'Partner',
    [Texts.InvitePopoverTitle]: 'A different organization is now available to you',
    [Texts.InvitePopoverText]: 'You can change your organization by clicking on your profile',
    [Texts.InvitePopoverAcceptButton]: 'Change now',
    [Texts.InvitePopoverCancelButton]: 'Cancel',
    [Texts.Projects]: 'Projects',
    [Texts.AddProject]: 'Add projects',
    [Texts.Platforms]: 'Platforms',
    [Texts.ManageProfile]: 'Manage profile',
    [Texts.SwitchTheme]: 'Switch theme',
    [Texts.Logout]: 'Logout',
    [Texts.Workspaces]: 'Workspaces',
    [Texts.AddWorkspace]: 'Add workspace',
    [Texts.Favorite]: 'Favorite',

    [Texts.FinancialMenuTitle]: 'Budget control',
    [Texts.FinancialMenuEyeButtonDataVisibleTip]: 'Hide balance in header',
    [Texts.FinancialMenuEyeButtonDataHiddenTip]: 'Show balance in header',
    [Texts.FinancialMenuBonusSign]: 'B',
    [Texts.FinancialMenuDrawerTitle]: 'Balance',
    [Texts.FinancialMenuTooltipMoreButton]: 'More details',
    [Texts.FinancialMenuBalanceAction]: 'Top up the balance',
    [Texts.FinancialMenuBonusesAction]: 'Enter promo code',
    [Texts.FinancialMenuGrantInfinity]: 'without a statute',
    [Texts.FinancialMenuNoGrants]: 'No grants yet',
    [Texts.FinancialMenuGrantStatusSpending]: 'Spending',
    [Texts.FinancialMenuGrantStatusNotSpending]: 'Not spending',
    [Texts.FinancialMenuGrantStatusNotStart]: 'No expiration date yet',
    [Texts.FinancialMenuAddServicesLink]: 'Connect services',
    [Texts.FinancialMenuGetGrant]: 'Get a grant',
    [Texts.FinancialMenuGrantIsOnTheWay]: 'The grant is on its way',
    [Texts.FinancialMenuStarterGrantName]: 'All services, without GPU',

    [Texts.Project]: 'Project',
    [Texts.Workspace]: 'Workspace',
    [Texts.Organization]: 'Organization',

    [Texts.SearchProjectsPlaceholder]: 'Search by projects',
    [Texts.SearchWorkspacesPlaceholder]: 'Search by workspaces',

    [Texts.ThemeModeLight]: 'Light',
    [Texts.ThemeModeDark]: 'Dark',
    [Texts.ThemeModeSystem]: 'System',
    [Texts.ThemeModeLabel]: 'Interface Theme',

    [Texts.PartnerPopoverTitle]: 'New organization available',
    [Texts.PartnerPopoverText]: 'The application for participation in the referral program has been approved',
    [Texts.PartnerPopoverDescription]:
      'Switch to this organization to start working in the partner account. You can switch between organizations in your profile or in the project selection menu.',
    [Texts.PartnerPopoverCancelButton]: `Don't show again`,
  },
};

export const textProvider = createTextProvider<Texts>(dictionary, 'navigation');
